.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/file_access/ascii_table.hpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/file_access/ascii_table.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iomanip>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <map>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'IceBRG_main/common\&.h'\fP
.br
\fC#include 'IceBRG_main/Eigen\&.hpp'\fP
.br
\fC#include 'IceBRG_main/container/table_typedefs\&.hpp'\fP
.br
\fC#include 'IceBRG_main/file_access/open_file\&.hpp'\fP
.br
\fC#include 'IceBRG_main/file_access/table_utility\&.hpp'\fP
.br
\fC#include 'IceBRG_main/file_access/trim_comments\&.hpp'\fP
.br
\fC#include 'IceBRG_main/math/misc_math\&.hpp'\fP
.br
\fC#include 'IceBRG_main/utility\&.hpp'\fP
.br
\fC#include 'IceBRG_main/vector/manipulations\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_BRG_ASCII_TABLE_H_INCLUDED_\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > void \fBIceBRG::print_table\fP (std::ostream &out_stream, const table_t< T > &data, const header_t &header=header_t(), const char major_tag=Eigen::ColMajor, const char precision=10)"
.br
.ti -1c
.RI "template<typename T > void \fBIceBRG::print_table\fP (const std::string &file_name, const table_t< T > &data, const header_t &header=header_t(), const char major_tag=Eigen::ColMajor)"
.br
.ti -1c
.RI "template<typename T > table_t< T > \fBIceBRG::load_table\fP (std::istream &fi, const char major_tag=Eigen::ColMajor, const T &default_value=T(), size_t min_length=0)"
.br
.ti -1c
.RI "template<typename T > table_t< T > \fBIceBRG::load_table\fP (const std::string &file_name, const char major_tag=Eigen::ColMajor, const T &default_value=T())"
.br
.ti -1c
.RI "header_t \fBIceBRG::load_header\fP (std::istream &table_stream)"
.br
.ti -1c
.RI "header_t \fBIceBRG::load_header\fP (const std::string &file_name)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _BRG_ASCII_TABLE_H_INCLUDED_"

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
