.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_physics/astro.h" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_physics/astro.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include 'IceBRG_main/common\&.h'\fP
.br
\fC#include 'IceBRG_main/units/unit_conversions\&.hpp'\fP
.br
\fC#include 'IceBRG_main/units/units\&.hpp'\fP
.br
\fC#include 'IceBRG_main/math/misc_math\&.hpp'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBIceBRG::redshift_obj\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_BRG_PI_DEFINED_\fP"
.br
.ti -1c
.RI "#define \fB_PHYS_VARS_DEFINED_\fP"
.br
.ti -1c
.RI "#define \fB_COSMO_VARS_DEFINED_\fP"
.br
.ti -1c
.RI "#define \fB_BRG_DEFAULT_ASTRO_VARS_DEFINED_\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const velocity_type \fBIceBRG::c\fP (\fBIceBRG::unitconv::ctomps\fP *mps)"
.br
.ti -1c
.RI "const inverse_time_type \fBIceBRG::H_0\fP (70 *unitconv::kmtom/unitconv::stos/unitconv::Mpctom/\fBIceBRG::second\fP)"
.br
.ti -1c
.RI "inverse_time_type \fBIceBRG::H\fP (const \fBflt_type\fP &z)"
.br
.ti -1c
.RI "custom_unit_type< 1, 0, 0,-1, 0 > \fBIceBRG::dfa\fP (const \fBflt_type\fP &z)"
.br
.ti -1c
.RI "distance_type \fBIceBRG::dfa\fP (const angle_type &da, const \fBflt_type\fP &z)"
.br
.ti -1c
.RI "distance_type \fBIceBRG::dfa\fP (const angle_type &a1, const angle_type &a2, const \fBflt_type\fP &z)"
.br
.ti -1c
.RI "distance_type \fBIceBRG::dfa\fP (const angle_type &a1x, const angle_type &a1y, const angle_type &a2x, const angle_type &a2y, const \fBflt_type\fP &z)"
.br
.ti -1c
.RI "custom_unit_type<-1, 0, 0, 1, 0 > \fBIceBRG::afd\fP (const \fBflt_type\fP &z)"
.br
.ti -1c
.RI "angle_type \fBIceBRG::afd\fP (const distance_type &dd, const \fBflt_type\fP &z)"
.br
.ti -1c
.RI "angle_type \fBIceBRG::afd\fP (const distance_type &d1, const distance_type &d2, const \fBflt_type\fP &z)"
.br
.ti -1c
.RI "angle_type \fBIceBRG::afd\fP (const distance_type &d1x, const distance_type &d1y, const distance_type &d2x, const distance_type &d2y, const \fBflt_type\fP &z)"
.br
.ti -1c
.RI "\fBflt_type\fP \fBIceBRG::zfa\fP (const \fBflt_type\fP &a)"
.br
.ti -1c
.RI "\fBflt_type\fP \fBIceBRG::afz\fP (const \fBflt_type\fP &z)"
.br
.ti -1c
.RI "time_type \fBIceBRG::tfz\fP (const \fBflt_type\fP &z)"
.br
.ti -1c
.RI "time_type \fBIceBRG::tfa\fP (const \fBflt_type\fP &z)"
.br
.ti -1c
.RI "\fBflt_type\fP \fBIceBRG::zft\fP (const time_type &t)"
.br
.ti -1c
.RI "\fBflt_type\fP \fBIceBRG::aft\fP (const time_type &t)"
.br
.ti -1c
.RI "distance_type \fBIceBRG::integrate_add\fP (const \fBflt_type\fP &z1, const \fBflt_type\fP &z2)"
.br
.ti -1c
.RI "distance_type \fBIceBRG::integrate_cmd\fP (const \fBflt_type\fP &z1, const \fBflt_type\fP &z2)"
.br
.ti -1c
.RI "distance_type \fBIceBRG::integrate_Ld\fP (const \fBflt_type\fP &z1, const \fBflt_type\fP &z2)"
.br
.ti -1c
.RI "distance_type \fBIceBRG::integrate_ltd\fP (const \fBflt_type\fP &z1, const \fBflt_type\fP &z2)"
.br
.ti -1c
.RI "distance_type \fBIceBRG::integrate_add\fP (const \fBflt_type\fP &z)"
.br
.ti -1c
.RI "distance_type \fBIceBRG::integrate_cmd\fP (const \fBflt_type\fP &z)"
.br
.ti -1c
.RI "distance_type \fBIceBRG::integrate_Ld\fP (const \fBflt_type\fP &z)"
.br
.ti -1c
.RI "distance_type \fBIceBRG::integrate_ltd\fP (const \fBflt_type\fP &z)"
.br
.ti -1c
.RI "distance_type \fBIceBRG::integrate_distance\fP (const \fBflt_type\fP &z1, const \fBflt_type\fP &z2, const \fBint_type\fP &mode, const \fBint_type\fP &resolution=10000)"
.br
.ti -1c
.RI "distance_type \fBIceBRG::ad_distance\fP (\fBflt_type\fP z1, \fBflt_type\fP z2=0)"
.br
.ti -1c
.RI "surface_density_type \fBIceBRG::sigma_crit\fP (const \fBflt_type\fP &z_lens, const \fBflt_type\fP &z_source)"
.br
.ti -1c
.RI "template<typename Tr1 , typename Td1 , typename Tr2 , typename Td2 > const Tr1 \fBIceBRG::skydist2d\fP (const Tr1 &ra1, const Td1 &dec1, const Tr2 &ra2, const Td2 &dec2)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBflt_type\fP & \fBpi\fP = M_PI"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::Gc\fP = 6\&.67384e-11"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::Omega_m\fP = 0\&.288"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::Omega_r\fP = 0\&.000086"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::Omega_k\fP = 0"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::Omega_l\fP = 1 - Omega_k - Omega_m - Omega_r"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::Omega_b\fP = 0\&.0472"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::sigma_8\fP = 0\&.830"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::n_s\fP = 0\&.971"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::default_c\fP = 6\&."
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::default_tau_factor\fP = 2\&."
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _BRG_DEFAULT_ASTRO_VARS_DEFINED_"

.SS "#define _BRG_PI_DEFINED_"
Constant Definitions 
.SS "#define _COSMO_VARS_DEFINED_"

.SS "#define _PHYS_VARS_DEFINED_"

.SH "Variable Documentation"
.PP 
.SS "const \fBflt_type\fP& pi = M_PI"

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
