.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_physics/astro_caches.cpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_physics/astro_caches.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <exception>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'IceBRG_main/common\&.h'\fP
.br
\fC#include 'IceBRG_main/math/cache/cache\&.hpp'\fP
.br
\fC#include 'IceBRG_main/math/cache/cache_2d\&.hpp'\fP
.br
\fC#include 'IceBRG_main/units/units\&.hpp'\fP
.br
\fC#include 'IceBRG_physics/astro\&.h'\fP
.br
\fC#include 'astro_caches\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDEFINE_BRG_CACHE_STATIC_VARS\fP (dfa_cache, 0, 5, 0\&.001)"
.br
.ti -1c
.RI "\fBDEFINE_BRG_CACHE_2D_STATIC_VARS\fP (add_cache, 0, 5, 0\&.01, 0, 5, 0\&.01)"
.br
.ti -1c
.RI "\fBDEFINE_BRG_CACHE_STATIC_VARS\fP (tfa_cache, 0\&.001, 1\&.02, 0\&.001)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "DEFINE_BRG_CACHE_2D_STATIC_VARS (add_cache, 0, 5, 0\&.01, 0, 5, 0\&.01)"

.SS "DEFINE_BRG_CACHE_STATIC_VARS (dfa_cache, 0, 5, 0\&.001)"
Static Class Initialisation 
.SS "DEFINE_BRG_CACHE_STATIC_VARS (tfa_cache, 0\&.001, 1\&.02, 0\&.001)"

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
