.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/file_access/binary_archive.hpp" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/file_access/binary_archive.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <limits>\fP
.br
\fC#include <string>\fP
.br
\fC#include <type_traits>\fP
.br
\fC#include <boost/archive/binary_oarchive\&.hpp>\fP
.br
\fC#include <boost/archive/binary_iarchive\&.hpp>\fP
.br
\fC#include '\&.\&./container/is_stl_container\&.hpp'\fP
.br
\fC#include 'IceBRG_main/file_access/open_file\&.hpp'\fP
.br
\fC#include 'IceBRG_main/utility\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , typename std::enable_if<!IceBRG::is_stl_container< T >::value, char >::type  = 0> void \fBIceBRG::binary_save\fP (boost::archive::binary_oarchive &ar, const T &obj)"
.br
.ti -1c
.RI "template<typename T , typename std::enable_if< IceBRG::is_stl_container< T >::value, char >::type  = 0, typename std::enable_if< std::is_same< typename T::value_type, bool >::value, char >::type  = 0> void \fBIceBRG::binary_save\fP (boost::archive::binary_oarchive &ar, const T &obj)"
.br
.ti -1c
.RI "template<typename T , typename std::enable_if< IceBRG::is_stl_container< T >::value, char >::type  = 0, typename std::enable_if<!std::is_same< typename T::value_type, bool >::value, char >::type  = 0> void \fBIceBRG::binary_save\fP (boost::archive::binary_oarchive &ar, const std::vector< T > &obj)"
.br
.ti -1c
.RI "template<typename T > void \fBIceBRG::binary_save\fP (std::ostream &out, const T &obj)"
.br
.ti -1c
.RI "template<typename T > void \fBIceBRG::binary_save\fP (const std::string &filename, const T &obj)"
.br
.ti -1c
.RI "template<typename T , typename T_test  = T, typename std::enable_if<!IceBRG::is_stl_container< T_test >::value, char >::type  = 0> T \fBIceBRG::binary_load\fP (boost::archive::binary_iarchive &ar)"
.br
.ti -1c
.RI "template<typename T , typename T_test  = T, typename std::enable_if< IceBRG::is_stl_container< T_test >::value, char >::type  = 0, typename std::enable_if< std::is_same< typename T_test::value_type, bool >::value, char >::type  = 0> T \fBIceBRG::binary_load\fP (boost::archive::binary_iarchive &ar)"
.br
.ti -1c
.RI "template<typename T > T \fBIceBRG::binary_load\fP (std::istream &in)"
.br
.ti -1c
.RI "template<typename T > T \fBIceBRG::binary_load\fP (const std::string &filename)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
