.TH "boost::accumulators::impl::sum_of_square_weights_accumulator< Sample >" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boost::accumulators::impl::sum_of_square_weights_accumulator< Sample > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sum_of_square_weights\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "typedef \fBdecltype\fP (Sample()*Sample()) result_type"
.br
.ti -1c
.RI "template<typename Args > \fBsum_of_square_weights_accumulator\fP (Args const &args)"
.br
.ti -1c
.RI "template<typename Args > void \fBoperator()\fP (Args const &args)"
.br
.ti -1c
.RI "result_type \fBresult\fP (dont_care) const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename Sample > template<typename Args > \fBboost::accumulators::impl::sum_of_square_weights_accumulator\fP< Sample >::\fBsum_of_square_weights_accumulator\fP (Args const &args)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename Sample > typedef \fBboost::accumulators::impl::sum_of_square_weights_accumulator\fP< Sample >::decltype (Sample()*Sample())"

.SS "template<typename Sample > template<typename Args > void \fBboost::accumulators::impl::sum_of_square_weights_accumulator\fP< Sample >::operator() (Args const &args)\fC [inline]\fP"

.SS "template<typename Sample > result_type \fBboost::accumulators::impl::sum_of_square_weights_accumulator\fP< Sample >::result (dont_care) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
