.TH "boost::accumulators::impl" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boost::accumulators::impl \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBeffective_count_accumulator\fP"
.br
.ti -1c
.RI "struct \fBerror_of_weighted_mean_accumulator\fP"
.br
.ti -1c
.RI "struct \fBmean_weight_accumulator\fP"
.br
.ti -1c
.RI "struct \fBsum_of_square_weights_accumulator\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
