.TH "boost::serialization" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boost::serialization \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class Archive , class T > void \fBsave\fP (Archive &ar, const boost::units::quantity< T > &g, const unsigned int version)"
.br
.ti -1c
.RI "template<class Archive , class T > void \fBload\fP (Archive &ar, boost::units::quantity< T > &g, const unsigned int version)"
.br
.ti -1c
.RI "template<class Archive , class T > void \fBserialize\fP (Archive &ar, boost::units::quantity< T > &g, const unsigned int file_version)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<class Archive , class T > void boost::serialization::load (Archive &ar, boost::units::quantity< T > &g, const unsigned intversion)"

.SS "template<class Archive , class T > void boost::serialization::save (Archive &ar, const boost::units::quantity< T > &g, const unsigned intversion)"

.SS "template<class Archive , class T > void boost::serialization::serialize (Archive &ar, boost::units::quantity< T > &g, const unsigned intfile_version)\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
