.TH "boost::accumulators::impl::mean_weight_accumulator< Sample >" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boost::accumulators::impl::mean_weight_accumulator< Sample > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mean_weight\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBflt_type\fP \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmean_weight_accumulator\fP (dont_care)"
.br
.ti -1c
.RI "template<typename Args > \fBresult_type\fP \fBresult\fP (Args const &args) const "
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename Sample > typedef \fBflt_type\fP \fBboost::accumulators::impl::mean_weight_accumulator\fP< Sample >::\fBresult_type\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename Sample > \fBboost::accumulators::impl::mean_weight_accumulator\fP< Sample >::\fBmean_weight_accumulator\fP (dont_care)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename Sample > template<typename Args > \fBresult_type\fP \fBboost::accumulators::impl::mean_weight_accumulator\fP< Sample >::result (Args const &args) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
