.TH "boost::accumulators::tag::mean_weight" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boost::accumulators::tag::mean_weight \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mean_weight\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef mpl::true_ \fBis_weight_accumulator\fP"
.br
.ti -1c
.RI "typedef 
.br
\fBaccumulators::impl::mean_weight_accumulator\fP
.br
< mpl::_1 > \fBimpl\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "typedef \fBaccumulators::impl::mean_weight_accumulator\fP< mpl::_1 > \fBboost::accumulators::tag::mean_weight::impl\fP"

.SS "typedef mpl::true_ \fBboost::accumulators::tag::mean_weight::is_weight_accumulator\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
