.TH "boost::accumulators::tag::error_of_weighted_mean" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boost::accumulators::tag::error_of_weighted_mean \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <error_of_weighted_mean\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef mpl::true_ \fBis_weight_accumulator\fP"
.br
.ti -1c
.RI "typedef 
.br
\fBaccumulators::impl::error_of_weighted_mean_accumulator\fP
.br
< mpl::_1 > \fBimpl\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "typedef \fBaccumulators::impl::error_of_weighted_mean_accumulator\fP< mpl::_1 > \fBboost::accumulators::tag::error_of_weighted_mean::impl\fP"

.SS "typedef mpl::true_ \fBboost::accumulators::tag::error_of_weighted_mean::is_weight_accumulator\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
