.TH "CFHTLenS_Mag_fetching_data" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFHTLenS_Mag_fetching_data \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBfields_lists\fP"
.br
.ti -1c
.RI "namespace \fBmagic_values\fP"
.br
.ti -1c
.RI "namespace \fBmatch_command\fP"
.br
.ti -1c
.RI "namespace \fBquery\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
