.TH "CFHTLenS_Mag_fetching_data.fields_lists" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFHTLenS_Mag_fetching_data.fields_lists \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBget_good_fields\fP"
.br
.ti -1c
.RI "def \fBget_bad_fields\fP"
.br
.ti -1c
.RI "def \fBget_all_fields\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.PP
.nf
fields_lists.py

    Created on 6 Jul 2015 as part of project CFHTLenS_catalogue_fetching
    
    This module contains hardcoded lists of the CFHTLenS field names.

    ---------------------------------------------------------------------

    Copyright (C) 2015  Bryan R. Gillis

    This program is free software: you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation, either version 3 of the License, or
     (at your option) any later version.

     This program is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>..fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "def CFHTLenS_Mag_fetching_data\&.fields_lists\&.get_all_fields (use_all_fields = \fCFalse\fP)"

.SS "def CFHTLenS_Mag_fetching_data\&.fields_lists\&.get_bad_fields (use_all_fields = \fCFalse\fP)"

.SS "def CFHTLenS_Mag_fetching_data\&.fields_lists\&.get_good_fields (use_all_fields = \fCFalse\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
