.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/common.h" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/common.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <complex>\fP
.br
\fC#include <vector>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_STACK_DEPTH\fP   100"
.br
.ti -1c
.RI "#define \fB_BRG_PI_DEFINED_\fP"
.br
.ti -1c
.RI "#define \fBMIN_DIVISOR\fP   1e-99"
.br
.ti -1c
.RI "#define \fBSMALL_FACTOR\fP   1e-9"
.br
.ti -1c
.RI "#define \fBFLT_ROUNDING_EPSILON\fP   10*FLT_EPSILON"
.br
.ti -1c
.RI "#define \fBROUNDING_EPSILON\fP   10*DBL_EPSILON"
.br
.ti -1c
.RI "#define \fBDBL_MAX_PRECISION\fP   14"
.br
.ti -1c
.RI "#define \fBBRG_UNIQUE_PTR\fP   std::auto_ptr"
.br
.ti -1c
.RI "#define \fBBRG_SHARED_PTR\fP   boost::shared_ptr"
.br
.ti -1c
.RI "#define \fBNULL\fP   (void *)0"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef double \fBflt_type\fP"
.br
.ti -1c
.RI "typedef long double \fBlong_flt_type\fP"
.br
.ti -1c
.RI "typedef int \fBint_type\fP"
.br
.ti -1c
.RI "typedef long int \fBlong_int_type\fP"
.br
.ti -1c
.RI "typedef short int \fBshort_int_type\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBunsigned_int_type\fP"
.br
.ti -1c
.RI "typedef long unsigned int \fBlong_unsigned_int_type\fP"
.br
.ti -1c
.RI "typedef short unsigned int \fBshort_unsigned_int_type\fP"
.br
.ti -1c
.RI "typedef std::complex< \fBflt_type\fP > \fBcomplex_type\fP"
.br
.ti -1c
.RI "typedef std::complex
.br
< \fBlong_flt_type\fP > \fBlong_complex_type\fP"
.br
.ti -1c
.RI "typedef std::vector< \fBint_type\fP > \fBint_vector_type\fP"
.br
.ti -1c
.RI "typedef std::vector
.br
< \fBlong_int_type\fP > \fBlong_int_vector_type\fP"
.br
.ti -1c
.RI "typedef std::vector
.br
< \fBshort_int_type\fP > \fBshort_int_vector_type\fP"
.br
.ti -1c
.RI "typedef std::vector
.br
< \fBunsigned_int_type\fP > \fBunsigned_int_vector_type\fP"
.br
.ti -1c
.RI "typedef std::vector
.br
< \fBlong_unsigned_int_type\fP > \fBlong_unsigned_int_vector_type\fP"
.br
.ti -1c
.RI "typedef std::vector
.br
< \fBshort_unsigned_int_type\fP > \fBshort_unsigned_int_vector_type\fP"
.br
.ti -1c
.RI "typedef std::vector< \fBflt_type\fP > \fBflt_vector_type\fP"
.br
.ti -1c
.RI "typedef std::vector
.br
< \fBlong_flt_type\fP > \fBlong_flt_vector_type\fP"
.br
.ti -1c
.RI "typedef std::vector< \fBcomplex_type\fP > \fBcomplex_vector_type\fP"
.br
.ti -1c
.RI "typedef std::vector
.br
< \fBlong_complex_type\fP > \fBlong_complex_vector_type\fP"
.br
.ti -1c
.RI "typedef std::make_signed
.br
< size_t >::type \fBssize_t\fP"
.br
.ti -1c
.RI "typedef \fBssize_t\fP \fBsize_type\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr \fBflt_type\fP \fBpi\fP = M_PI"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _BRG_PI_DEFINED_"

.SS "#define BRG_SHARED_PTR   boost::shared_ptr"

.SS "#define BRG_UNIQUE_PTR   std::auto_ptr"

.SS "#define DBL_MAX_PRECISION   14"

.SS "#define FLT_ROUNDING_EPSILON   10*FLT_EPSILON"

.SS "#define MAX_STACK_DEPTH   100"

.SS "#define MIN_DIVISOR   1e-99"

.SS "#define NULL   (void *)0"

.SS "#define ROUNDING_EPSILON   10*DBL_EPSILON"

.SS "#define SMALL_FACTOR   1e-9"

.SH "Typedef Documentation"
.PP 
.SS "typedef std::complex<\fBflt_type\fP> \fBcomplex_type\fP"

.SS "typedef std::vector<\fBcomplex_type\fP> \fBcomplex_vector_type\fP"

.SS "typedef double \fBflt_type\fP"

.SS "typedef std::vector<\fBflt_type\fP> \fBflt_vector_type\fP"

.SS "typedef int \fBint_type\fP"

.SS "typedef std::vector<\fBint_type\fP> \fBint_vector_type\fP"

.SS "typedef std::complex<\fBlong_flt_type\fP> \fBlong_complex_type\fP"

.SS "typedef std::vector<\fBlong_complex_type\fP> \fBlong_complex_vector_type\fP"

.SS "typedef long double \fBlong_flt_type\fP"

.SS "typedef std::vector<\fBlong_flt_type\fP> \fBlong_flt_vector_type\fP"

.SS "typedef long int \fBlong_int_type\fP"

.SS "typedef std::vector<\fBlong_int_type\fP> \fBlong_int_vector_type\fP"

.SS "typedef long unsigned int \fBlong_unsigned_int_type\fP"

.SS "typedef std::vector<\fBlong_unsigned_int_type\fP> \fBlong_unsigned_int_vector_type\fP"

.SS "typedef short int \fBshort_int_type\fP"

.SS "typedef std::vector<\fBshort_int_type\fP> \fBshort_int_vector_type\fP"

.SS "typedef short unsigned int \fBshort_unsigned_int_type\fP"

.SS "typedef std::vector<\fBshort_unsigned_int_type\fP> \fBshort_unsigned_int_vector_type\fP"

.SS "typedef \fBssize_t\fP \fBsize_type\fP"

.SS "typedef std::make_signed<size_t>::type \fBssize_t\fP"

.SS "typedef unsigned int \fBunsigned_int_type\fP"

.SS "typedef std::vector<\fBunsigned_int_type\fP> \fBunsigned_int_vector_type\fP"

.SH "Variable Documentation"
.PP 
.SS "constexpr \fBflt_type\fP pi = M_PI"

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
