.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/command_line.hpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/command_line.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <functional>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <string>\fP
.br
\fC#include <boost/lexical_cast\&.hpp>\fP
.br
\fC#include <boost/type_index\&.hpp>\fP
.br
\fC#include 'common\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename To > To \fBIceBRG::get_cline_arg\fP (const int &argc, const char *argv[], const int &i)"
.br
.ti -1c
.RI "template<typename To > To \fBIceBRG::get_cline_arg\fP (const int &argc, const char *argv[], const int &i, const std::function< bool(const To &)> &test)"
.br
.ti -1c
.RI "template<typename To > To \fBIceBRG::get_cline_arg\fP (const int &argc, const char *argv[], const int &i, const To &default_out)"
.br
.ti -1c
.RI "template<typename To > To \fBIceBRG::get_cline_arg\fP (const int &argc, const char *argv[], const int &i, const std::function< bool(const To &)> &test, const To &default_out)"
.br
.ti -1c
.RI "template<typename To , typename\&.\&.\&. Tos> To \fBIceBRG::get_cline_arg\fP (const int &argc, const char *argv[], const int &i, const std::function< bool(const To &)> &test, const To &primary_default_out, const To &secondary_default_out, Tos\&.\&.\&.other_default_outs)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
