.TH "/disk2/brg/git/Magnification_Public/config.h" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/config.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAVE_BOOST\fP"
.br
.ti -1c
.RI "#define \fBHAVE_BOOST_SERIALIZATION\fP"
.br
.ti -1c
.RI "#define \fBHAVE_CCFITS\fP"
.br
.ti -1c
.RI "#define \fBHAVE_CCFITS_CCFITS_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_EIGEN_CORE\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FLOOR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FORK\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_INTTYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMORY_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MODF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_POW\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_PTRDIFF_T\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SQRT\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDDEF_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDINT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDLIB_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRINGS_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRING_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_STAT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_TYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_UNISTD_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_VFORK\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_WORKING_FORK\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_WORKING_VFORK\fP   1"
.br
.ti -1c
.RI "#define \fBPACKAGE\fP   'cfhtlens_magnification'"
.br
.ti -1c
.RI "#define \fBPACKAGE_BUGREPORT\fP   'brg@roe\&.ac\&.uk'"
.br
.ti -1c
.RI "#define \fBPACKAGE_NAME\fP   'CFHTLenS_Magnification'"
.br
.ti -1c
.RI "#define \fBPACKAGE_STRING\fP   'CFHTLenS_Magnification 0\&.9\&.0'"
.br
.ti -1c
.RI "#define \fBPACKAGE_TARNAME\fP   'cfhtlens_magnification'"
.br
.ti -1c
.RI "#define \fBPACKAGE_URL\fP   ''"
.br
.ti -1c
.RI "#define \fBPACKAGE_VERSION\fP   '0\&.9\&.0'"
.br
.ti -1c
.RI "#define \fBSTDC_HEADERS\fP   1"
.br
.ti -1c
.RI "#define \fBVERSION\fP   '0\&.9\&.0'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HAVE_BOOST"

.SS "#define HAVE_BOOST_SERIALIZATION"

.SS "#define HAVE_CCFITS"

.SS "#define HAVE_CCFITS_CCFITS_H   1"

.SS "#define HAVE_EIGEN_CORE   1"

.SS "#define HAVE_FLOOR   1"

.SS "#define HAVE_FORK   1"

.SS "#define HAVE_INTTYPES_H   1"

.SS "#define HAVE_MEMORY_H   1"

.SS "#define HAVE_MODF   1"

.SS "#define HAVE_POW   1"

.SS "#define HAVE_PTRDIFF_T   1"

.SS "#define HAVE_SQRT   1"

.SS "#define HAVE_STDDEF_H   1"

.SS "#define HAVE_STDINT_H   1"

.SS "#define HAVE_STDLIB_H   1"

.SS "#define HAVE_STRING_H   1"

.SS "#define HAVE_STRINGS_H   1"

.SS "#define HAVE_SYS_STAT_H   1"

.SS "#define HAVE_SYS_TYPES_H   1"

.SS "#define HAVE_UNISTD_H   1"

.SS "#define HAVE_VFORK   1"

.SS "#define HAVE_WORKING_FORK   1"

.SS "#define HAVE_WORKING_VFORK   1"

.SS "#define PACKAGE   'cfhtlens_magnification'"

.SS "#define PACKAGE_BUGREPORT   'brg@roe\&.ac\&.uk'"

.SS "#define PACKAGE_NAME   'CFHTLenS_Magnification'"

.SS "#define PACKAGE_STRING   'CFHTLenS_Magnification 0\&.9\&.0'"

.SS "#define PACKAGE_TARNAME   'cfhtlens_magnification'"

.SS "#define PACKAGE_URL   ''"

.SS "#define PACKAGE_VERSION   '0\&.9\&.0'"

.SS "#define STDC_HEADERS   1"

.SS "#define VERSION   '0\&.9\&.0'"

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
