.TH "/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_corr_func/src/corr_func_config.h" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_corr_func/src/corr_func_config.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cassert>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include 'IceBRG_main/common\&.h'\fP
.br
\fC#include 'IceBRG_main/units/unit_conversions\&.hpp'\fP
.br
\fC#include 'IceBRG_main/units/units\&.hpp'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBcorr_func_config\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
