.TH "/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_catalogue_filtering/src/correct_redshift_bias.h" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_catalogue_filtering/src/correct_redshift_bias.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'IceBRG_main/math/interpolator/interpolator\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBredshift_calibrator_wrapper\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcorrect_redshift_bias\fP (std::vector< std::string > &redshifts)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void correct_redshift_bias (std::vector< std::string > &redshifts)"

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
