.TH "corr_func_config" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
corr_func_config \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <corr_func_config\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcorr_func_config\fP (const int argc=0, const char *argv[]=nullptr)"
.br
.ti -1c
.RI "virtual \fB~corr_func_config\fP ()"
.br
.ti -1c
.RI "\fBcorr_func_config\fP (const int argc=0, const char *argv[]=nullptr)"
.br
.ti -1c
.RI "virtual \fB~corr_func_config\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBIceBRG::distance_type\fP \fBR_min\fP"
.br
.ti -1c
.RI "\fBIceBRG::distance_type\fP \fBR_max\fP"
.br
.ti -1c
.RI "\fBIceBRG::mass_type\fP \fBm_min\fP"
.br
.ti -1c
.RI "\fBIceBRG::mass_type\fP \fBm_max\fP"
.br
.ti -1c
.RI "double \fBz_min\fP"
.br
.ti -1c
.RI "double \fBz_max\fP"
.br
.ti -1c
.RI "double \fBmag_min\fP"
.br
.ti -1c
.RI "double \fBmag_max\fP"
.br
.ti -1c
.RI "size_t \fBR_bins\fP"
.br
.ti -1c
.RI "size_t \fBm_bins\fP"
.br
.ti -1c
.RI "size_t \fBz_bins\fP"
.br
.ti -1c
.RI "size_t \fBmag_bins\fP"
.br
.ti -1c
.RI "bool \fBR_log\fP"
.br
.ti -1c
.RI "bool \fBm_log\fP"
.br
.ti -1c
.RI "bool \fBz_log\fP"
.br
.ti -1c
.RI "bool \fBmag_log\fP"
.br
.ti -1c
.RI "double \fBz_buffer\fP"
.br
.ti -1c
.RI "short \fBlensing_style\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr size_t \fBnum_config_params\fP = 18"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "corr_func_config::corr_func_config (const intargc = \fC0\fP, const char *argv[] = \fCnullptr\fP)"

.SS "virtual corr_func_config::~corr_func_config ()\fC [inline]\fP, \fC [virtual]\fP"

.SS "corr_func_config::corr_func_config (const intargc = \fC0\fP, const char *argv[] = \fCnullptr\fP)"

.SS "virtual corr_func_config::~corr_func_config ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Field Documentation"
.PP 
.SS "short corr_func_config::lensing_style"

.SS "size_t corr_func_config::m_bins"

.SS "bool corr_func_config::m_log"

.SS "\fBIceBRG::mass_type\fP corr_func_config::m_max"

.SS "\fBIceBRG::mass_type\fP corr_func_config::m_min"

.SS "size_t corr_func_config::mag_bins"

.SS "bool corr_func_config::mag_log"

.SS "double corr_func_config::mag_max"

.SS "double corr_func_config::mag_min"

.SS "static constexpr size_t corr_func_config::num_config_params = 18\fC [static]\fP"

.SS "size_t corr_func_config::R_bins"

.SS "bool corr_func_config::R_log"

.SS "\fBIceBRG::distance_type\fP corr_func_config::R_max"

.SS "\fBIceBRG::distance_type\fP corr_func_config::R_min"

.SS "size_t corr_func_config::z_bins"

.SS "double corr_func_config::z_buffer"

.SS "bool corr_func_config::z_log"

.SS "double corr_func_config::z_max"

.SS "double corr_func_config::z_min"


.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
