.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/math/calculus/differentiate.hpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/math/calculus/differentiate.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'IceBRG_main/common\&.h'\fP
.br
\fC#include 'IceBRG_main/math/misc_math\&.hpp'\fP
.br
\fC#include 'IceBRG_main/math/safe_math\&.hpp'\fP
.br
\fC#include 'IceBRG_main/utility\&.hpp'\fP
.br
\fC#include 'IceBRG_main/vector/make_vector\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename f , typename T > T \fBIceBRG::differentiate\fP (const f *func, const T &in_param, const \fBint_type\fP order=1, const \fBflt_type\fP &power=1, const T &factor=\fBSMALL_FACTOR\fP)"
.br
.ti -1c
.RI "template<typename f , typename T > std::vector< std::vector< T > > \fBIceBRG::differentiate\fP (const f *func, const std::vector< T > &in_params, const \fBint_type\fP order=1, const \fBflt_type\fP &power=1)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
