.TH "/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_fit_lensing_models/fitting_bin.hpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_fit_lensing_models/fitting_bin.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <utility>\fP
.br
\fC#include 'common\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBfitting_bin\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
