.TH "fitting_bin" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fitting_bin \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fitting_bin\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Tx  = flt_type, typename Ty_mean  = flt_type, typename Ty_stderr  = flt_type> \fBfitting_bin\fP (Tx &&\fBx\fP=0\&., Ty_mean &&\fBy_mean\fP=0\&., Ty_stderr &&\fBy_stderr\fP=1\&.)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBflt_type\fP \fBx\fP"
.br
.ti -1c
.RI "\fBflt_type\fP \fBy_mean\fP"
.br
.ti -1c
.RI "\fBflt_type\fP \fBy_stderr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename Tx  = flt_type, typename Ty_mean  = flt_type, typename Ty_stderr  = flt_type> fitting_bin::fitting_bin (Tx &&x = \fC0\&.\fP, Ty_mean &&y_mean = \fC0\&.\fP, Ty_stderr &&y_stderr = \fC1\&.\fP)\fC [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBflt_type\fP fitting_bin::x"

.SS "\fBflt_type\fP fitting_bin::y_mean"

.SS "\fBflt_type\fP fitting_bin::y_stderr"


.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
