.TH "get_masks" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
get_masks \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBbase_good_fields_filename\fP = '/disk2/brg/git/CFHTLenS_cat/Data/good_fields_list\&.txt'"
.br
.ti -1c
.RI "string \fBbase_bad_fields_filename\fP = '/disk2/brg/git/CFHTLenS_cat/Data/bad_fields_list\&.txt'"
.br
.ti -1c
.RI "string \fBbase_command_filename\fP = '/disk2/brg/git/CFHTLenS_cat/CFHTLenS_mask_testing/src/wget_cmd\&.txt'"
.br
.ti -1c
.RI "string \fBfield_replace_tag\fP = 'REPLACEME_FIELD'"
.br
.ti -1c
.RI "string \fBi_or_y_replace_tag\fP = 'REPLACEME_I_OR_Y'"
.br
.ti -1c
.RI "string \fBoutput_replace_tag\fP = 'REPLACEME_OUTPUT_NAME'"
.br
.ti -1c
.RI "string \fBmask_output_path\fP = '/disk2/brg/git/CFHTLenS_cat/Data/masks/'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def get_masks\&.main (argv)"
.PP
.nf
TODO Docstring for main..fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "string get_masks\&.base_bad_fields_filename = '/disk2/brg/git/CFHTLenS_cat/Data/bad_fields_list\&.txt'"

.SS "string get_masks\&.base_command_filename = '/disk2/brg/git/CFHTLenS_cat/CFHTLenS_mask_testing/src/wget_cmd\&.txt'"

.SS "string get_masks\&.base_good_fields_filename = '/disk2/brg/git/CFHTLenS_cat/Data/good_fields_list\&.txt'"

.SS "string get_masks\&.field_replace_tag = 'REPLACEME_FIELD'"

.SS "string get_masks\&.i_or_y_replace_tag = 'REPLACEME_I_OR_Y'"

.SS "string get_masks\&.mask_output_path = '/disk2/brg/git/CFHTLenS_cat/Data/masks/'"

.SS "string get_masks\&.output_replace_tag = 'REPLACEME_OUTPUT_NAME'"

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
