.TH "/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_catalogue_filtering/src/get_filtered_indices.h" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_catalogue_filtering/src/get_filtered_indices.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'IceBRG_main/container/labeled_array\&.hpp'\fP
.br
\fC#include 'IceBRG_main/container/table_typedefs\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmove_y_column_to_i\fP (\fBIceBRG::labeled_array\fP< double > &map)"
.br
.ti -1c
.RI "std::vector< size_t > \fBget_good_lenses\fP (const \fBIceBRG::labeled_array\fP< double > &map, const std::vector< std::vector< bool >> good_pixels)"
.br
.ti -1c
.RI "std::vector< size_t > \fBget_good_sources\fP (const \fBIceBRG::labeled_array\fP< double > &map, const std::vector< std::vector< bool >> good_pixels)"
.br
.ti -1c
.RI "bool \fBgalaxy_passes_lens_filter\fP (const \fBIceBRG::labeled_array\fP< double >::const_row_reference &galaxy)"
.br
.ti -1c
.RI "bool \fBgalaxy_passes_source_filter\fP (const \fBIceBRG::labeled_array\fP< double >::const_row_reference &galaxy)"
.br
.ti -1c
.RI "bool \fBgalaxy_passes_global_filter\fP (const \fBIceBRG::labeled_array\fP< double >::const_row_reference &galaxy)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool galaxy_passes_global_filter (const \fBIceBRG::labeled_array\fP< double >::const_row_reference &galaxy)"

.SS "bool galaxy_passes_lens_filter (const \fBIceBRG::labeled_array\fP< double >::const_row_reference &galaxy)"

.SS "bool galaxy_passes_source_filter (const \fBIceBRG::labeled_array\fP< double >::const_row_reference &galaxy)"

.SS "std::vector<size_t> get_good_lenses (const \fBIceBRG::labeled_array\fP< double > &map, const std::vector< std::vector< bool >>good_pixels)"

.SS "std::vector<size_t> get_good_sources (const \fBIceBRG::labeled_array\fP< double > &map, const std::vector< std::vector< bool >>good_pixels)"

.SS "void move_y_column_to_i (\fBIceBRG::labeled_array\fP< double > &map)"

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
