.TH "/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_make_mock_cats/get_ra_dec.h" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_make_mock_cats/get_ra_dec.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::vector< std::pair
.br
< std::pair< double, double >
.br
, std::pair< double, double > > > \fBget_ra_dec\fP (const std::string &field_name, const std::vector< std::pair< double, double >> &xp_yp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::vector<std::pair<std::pair<double,double>,std::pair<double,double> > > get_ra_dec (const std::string &field_name, const std::vector< std::pair< double, double >> &xp_yp)"

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
