.TH "get_fields" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
get_fields \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBuse_temp_fields\fP = True"
.br
.ti -1c
.RI "string \fBbase_good_fields_filename\fP = '/disk2/brg/git/CFHTLenS_cat/Data/good_fields_list\&.txt'"
.br
.ti -1c
.RI "string \fBbase_bad_fields_filename\fP = '/disk2/brg/git/CFHTLenS_cat/Data/bad_fields_list\&.txt'"
.br
.ti -1c
.RI "string \fBtemp_fields_filename\fP = '/disk2/brg/git/CFHTLenS_cat/Data/temp_fields_list\&.txt'"
.br
.ti -1c
.RI "string \fBbase_query_filename\fP = '/disk2/brg/git/CFHTLenS_cat/CFHTLenS_catalogue_filtering/src/base_query\&.txt'"
.br
.ti -1c
.RI "string \fBbase_command_filename\fP = '/disk2/brg/git/CFHTLenS_cat/CFHTLenS_catalogue_filtering/src/wget_cmd\&.txt'"
.br
.ti -1c
.RI "string \fBquery_field_replace_tag\fP = 'REPLACEME_FIELD'"
.br
.ti -1c
.RI "string \fBquery_i_or_y_replace_tag\fP = 'REPLACEME_I_OR_Y'"
.br
.ti -1c
.RI "string \fBcommand_output_replace_tag\fP = 'REPLACEME_OUTPUT_NAME'"
.br
.ti -1c
.RI "string \fBcommand_query_replace_tag\fP = 'REPLACEME_QUERY'"
.br
.ti -1c
.RI "string \fBdata_table_path\fP = '/disk2/brg/git/CFHTLenS_cat/Data/full_tables/'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def get_fields\&.main (argv)"
.PP
.nf
TODO Docstring for main..fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "string get_fields\&.base_bad_fields_filename = '/disk2/brg/git/CFHTLenS_cat/Data/bad_fields_list\&.txt'"

.SS "string get_fields\&.base_command_filename = '/disk2/brg/git/CFHTLenS_cat/CFHTLenS_catalogue_filtering/src/wget_cmd\&.txt'"

.SS "string get_fields\&.base_good_fields_filename = '/disk2/brg/git/CFHTLenS_cat/Data/good_fields_list\&.txt'"

.SS "string get_fields\&.base_query_filename = '/disk2/brg/git/CFHTLenS_cat/CFHTLenS_catalogue_filtering/src/base_query\&.txt'"

.SS "string get_fields\&.command_output_replace_tag = 'REPLACEME_OUTPUT_NAME'"

.SS "string get_fields\&.command_query_replace_tag = 'REPLACEME_QUERY'"

.SS "string get_fields\&.data_table_path = '/disk2/brg/git/CFHTLenS_cat/Data/full_tables/'"

.SS "string get_fields\&.query_field_replace_tag = 'REPLACEME_FIELD'"

.SS "string get_fields\&.query_i_or_y_replace_tag = 'REPLACEME_I_OR_Y'"

.SS "string get_fields\&.temp_fields_filename = '/disk2/brg/git/CFHTLenS_cat/Data/temp_fields_list\&.txt'"

.SS "get_fields\&.use_temp_fields = True"

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
