.TH "/disk2/brg/git/Magnification_Public/src/lib/CFHTLenS_include/get_data_directory.hpp" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/CFHTLenS_include/get_data_directory.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'IceBRG_main/command_line\&.hpp'\fP
.br
\fC#include 'IceBRG_main/error_handling\&.h'\fP
.br
\fC#include 'IceBRG_main/join_path\&.hpp'\fP
.br
\fC#include 'IceBRG_main/file_access/open_file\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBget_data_directory\fP (const int &argc, const char *argv[], std::ifstream *fi)"
.br
.ti -1c
.RI "std::string \fBget_data_directory\fP (const int &argc, const char *argv[])"
.br
.ti -1c
.RI "std::string \fBget_data_directory\fP (const int &argc, const char *argv[], std::ifstream &fi)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::string \fBprimary_default_data_directory\fP = '\&./Data/'"
.br
.ti -1c
.RI "const std::string \fBsecondary_default_data_directory\fP = '\&.\&./Data/'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::string get_data_directory (const int &argc, const char *argv[], std::ifstream *fi)\fC [inline]\fP"

.SS "std::string get_data_directory (const int &argc, const char *argv[])\fC [inline]\fP"

.SS "std::string get_data_directory (const int &argc, const char *argv[], std::ifstream &fi)\fC [inline]\fP"

.SH "Variable Documentation"
.PP 
.SS "const std::string primary_default_data_directory = '\&./Data/'"

.SS "const std::string secondary_default_data_directory = '\&.\&./Data/'"

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
