.TH "/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_gg_lensing/gg_lensing_config.cpp" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_gg_lensing/gg_lensing_config.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <limits>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'IceBRG_main/error_handling\&.h'\fP
.br
\fC#include 'IceBRG_main/file_access/open_file\&.hpp'\fP
.br
\fC#include 'IceBRG_main/file_access/trim_comments\&.hpp'\fP
.br
\fC#include 'IceBRG_main/lexical_cast\&.hpp'\fP
.br
\fC#include 'IceBRG_main/units/unit_conversions\&.hpp'\fP
.br
\fC#include 'IceBRG_main/units/units\&.hpp'\fP
.br
\fC#include 'gg_lensing_config\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
