.TH "IceBRG::pair_bin_summary" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IceBRG::pair_bin_summary \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pair_bin_summary\&.h>\fP
.PP
Inherited by \fBIceBRG::pair_bin\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpair_bin_summary\fP (const \fBdistance_type\fP &init_R_min=0, const \fBdistance_type\fP &init_R_max=0, const \fBmass_type\fP &init_m_min=0 *\fBkg\fP, const \fBmass_type\fP &init_m_max=0 *\fBkg\fP, const \fBflt_type\fP &init_z_min=0, const \fBflt_type\fP &init_z_max=0, const \fBflt_type\fP &init_mag_min=0, const \fBflt_type\fP &init_mag_max=0)"
.br
.ti -1c
.RI "\fBpair_bin_summary\fP (const \fBpair_bin\fP &bin)"
.br
.ti -1c
.RI "\fBpair_bin_summary\fP (std::istream &in)"
.br
.ti -1c
.RI "\fBpair_bin_summary\fP (std::string &filename)"
.br
.ti -1c
.RI "\fBpair_bin_summary\fP & \fBoperator=\fP (const \fBpair_bin\fP &bin)"
.br
.ti -1c
.RI "virtual \fB~pair_bin_summary\fP ()"
.br
.ti -1c
.RI "template<typename T1 , typename T2 > void \fBset_R_limits\fP (T1 &&\fBR_min\fP, T2 &&\fBR_max\fP)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 > void \fBset_m_limits\fP (T1 &&\fBm_min\fP, T2 &&\fBm_max\fP)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 > void \fBset_z_limits\fP (T1 &&\fBz_min\fP, T2 &&\fBz_max\fP)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 > void \fBset_mag_limits\fP (T1 &&\fBmag_min\fP, T2 &&\fBmag_max\fP)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 > void \fBset_limits\fP (T1 &&\fBR_min\fP, T2 &&\fBR_max\fP, T3 &&\fBm_min\fP, T4 &&\fBm_max\fP, T5 &&\fBz_min\fP, T6 &&\fBz_max\fP, T7 &&\fBmag_min\fP, T8 &&\fBmag_max\fP)"
.br
.ti -1c
.RI "virtual void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBfixbad\fP ()"
.br
.ti -1c
.RI "virtual \fBssize_t\fP \fBpair_count\fP () const "
.br
.ti -1c
.RI "virtual \fBssize_t\fP \fBshear_pair_count\fP () const "
.br
.ti -1c
.RI "virtual \fBssize_t\fP \fBmagf_pair_count\fP () const "
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBeffective_pair_count\fP () const "
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBshear_effective_pair_count\fP () const "
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBsum_of_weights\fP () const "
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBshear_sum_of_weights\fP () const "
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBmagf_sum_of_weights\fP () const "
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBsum_of_square_weights\fP () const "
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBshear_sum_of_square_weights\fP () const "
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBmagf_sum_of_square_weights\fP () const "
.br
.ti -1c
.RI "const \fBdistance_type\fP & \fBR_min\fP () const "
.br
.ti -1c
.RI "const \fBdistance_type\fP & \fBR_max\fP () const "
.br
.ti -1c
.RI "\fBdistance_type\fP \fBR_mid\fP () const "
.br
.ti -1c
.RI "\fBdistance_type\fP \fBR_amid\fP () const "
.br
.ti -1c
.RI "virtual \fBdistance_type\fP \fBR_mean\fP () const "
.br
.ti -1c
.RI "virtual \fBdistance_type\fP \fBshear_R_mean\fP () const "
.br
.ti -1c
.RI "virtual \fBdistance_type\fP \fBmagf_R_mean\fP () const "
.br
.ti -1c
.RI "const \fBmass_type\fP & \fBm_min\fP () const "
.br
.ti -1c
.RI "const \fBmass_type\fP & \fBm_max\fP () const "
.br
.ti -1c
.RI "\fBmass_type\fP \fBm_mid\fP () const "
.br
.ti -1c
.RI "virtual \fBmass_type\fP \fBlens_m_mean\fP () const "
.br
.ti -1c
.RI "virtual \fBmass_type\fP \fBshear_lens_m_mean\fP () const "
.br
.ti -1c
.RI "virtual \fBmass_type\fP \fBmagf_lens_m_mean\fP () const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBz_min\fP () const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBz_max\fP () const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBz_mid\fP () const "
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBlens_z_mean\fP () const "
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBshear_lens_z_mean\fP () const "
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBmagf_lens_z_mean\fP () const "
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBsource_z_mean\fP () const "
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBshear_source_z_mean\fP () const "
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBmagf_source_z_mean\fP () const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBmag_min\fP () const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBmag_max\fP () const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBmag_mid\fP () const "
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBlens_mag_mean\fP () const "
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBshear_lens_mag_mean\fP () const "
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBmagf_lens_mag_mean\fP () const "
.br
.ti -1c
.RI "\fBsurface_density_type\fP \fBshear_sigma_crit\fP () const "
.br
.ti -1c
.RI "\fBsurface_density_type\fP \fBmagf_sigma_crit\fP () const "
.br
.ti -1c
.RI "virtual \fBsurface_density_type\fP \fBdelta_Sigma_t_mean\fP () const "
.br
.ti -1c
.RI "virtual \fBsurface_density_type\fP \fBdelta_Sigma_x_mean\fP () const "
.br
.ti -1c
.RI "virtual custom_unit_type<-4, 0, 2, 0, 0 > \fBdelta_Sigma_t_mean_square\fP () const "
.br
.ti -1c
.RI "virtual custom_unit_type<-4, 0, 2, 0, 0 > \fBdelta_Sigma_x_mean_square\fP () const "
.br
.ti -1c
.RI "virtual \fBsurface_density_type\fP \fBdelta_Sigma_t_std\fP () const "
.br
.ti -1c
.RI "virtual \fBsurface_density_type\fP \fBdelta_Sigma_x_std\fP () const "
.br
.ti -1c
.RI "virtual \fBsurface_density_type\fP \fBdelta_Sigma_t_stderr\fP () const "
.br
.ti -1c
.RI "virtual \fBsurface_density_type\fP \fBdelta_Sigma_x_stderr\fP () const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBgamma_t_mean\fP () const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBgamma_x_mean\fP () const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBgamma_mean\fP () const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBgamma_mean_square\fP () const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBgamma_t_stderr\fP () const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBgamma_x_stderr\fP () const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBgamma_stderr\fP () const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBgamma_square_stderr\fP () const "
.br
.ti -1c
.RI "\fBsurface_density_type\fP \fBmodel_delta_Sigma_t\fP (const \fBflt_type\fP &MLratio_1h=50\&., const \fBmass_type\fP &mean_group_mass=1e14 *unitconv::Msuntokg *kg, const flt_type &sat_frac=0\&.2) const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBmodel_gamma_t\fP (const \fBflt_type\fP &MLratio_1h=50\&., const \fBmass_type\fP &mean_group_mass=1e14 *unitconv::Msuntokg *kg, const flt_type &sat_frac=0\&.2) const "
.br
.ti -1c
.RI "\fBsurface_density_type\fP \fBmodel_1h_delta_Sigma_t\fP (const \fBflt_type\fP &MLratio_1h=50\&.) const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBmodel_1h_gamma_t\fP (const \fBflt_type\fP &MLratio_1h=50\&.) const "
.br
.ti -1c
.RI "\fBsurface_density_type\fP \fBmodel_offset_delta_Sigma_t\fP (const \fBmass_type\fP &mean_group_mass=1e14 *unitconv::Msuntokg *kg, const flt_type &sat_frac=0\&.2) const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBmodel_offset_gamma_t\fP (const \fBmass_type\fP &mean_group_mass=1e14 *unitconv::Msuntokg *kg, const flt_type &sat_frac=0\&.2) const "
.br
.ti -1c
.RI "custom_unit_type< 0, 0, 0, 2, 0 > \fBarea_per_lens\fP () const "
.br
.ti -1c
.RI "virtual custom_unit_type< 0, 0, 0, 2, 0 > \fBarea\fP () const "
.br
.ti -1c
.RI "virtual \fBssize_t\fP \fBnum_lenses\fP () const "
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBmagf_effective_num_lenses\fP () const "
.br
.ti -1c
.RI "virtual \fBssize_t\fP \fBmagf_num_lenses\fP () const "
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBmu_hat\fP () const "
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBmu_square_hat\fP () const "
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBmu_W\fP () const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBmu_std\fP () const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBmu_stderr\fP () const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBkappa\fP () const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBkappa_stderr\fP () const "
.br
.ti -1c
.RI "\fBsurface_density_type\fP \fBSigma\fP () const "
.br
.ti -1c
.RI "\fBsurface_density_type\fP \fBSigma_stderr\fP () const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBmodel_mu\fP (const \fBflt_type\fP &MLratio_1h=50\&., const \fBmass_type\fP &mean_group_mass=1e14 *unitconv::Msuntokg *kg, const flt_type &sat_frac=0\&.2) const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBmodel_kappa\fP (const \fBflt_type\fP &MLratio_1h=50\&., const \fBmass_type\fP &mean_group_mass=1e14 *unitconv::Msuntokg *kg, const flt_type &sat_frac=0\&.2) const "
.br
.ti -1c
.RI "\fBsurface_density_type\fP \fBmodel_Sigma\fP (const \fBflt_type\fP &MLratio_1h=50\&., const \fBmass_type\fP &mean_group_mass=1e14 *unitconv::Msuntokg *kg, const flt_type &sat_frac=0\&.2) const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBmodel_1h_mu\fP (const \fBflt_type\fP &MLratio_1h=50\&.) const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBmodel_1h_kappa\fP (const \fBflt_type\fP &MLratio_1h=50\&.) const "
.br
.ti -1c
.RI "\fBsurface_density_type\fP \fBmodel_1h_Sigma\fP (const \fBflt_type\fP &MLratio_1h=50\&.) const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBmodel_offset_mu\fP (const \fBmass_type\fP &mean_group_mass=1e14 *unitconv::Msuntokg *kg, const flt_type &sat_frac=0\&.2) const "
.br
.ti -1c
.RI "\fBflt_type\fP \fBmodel_offset_kappa\fP (const \fBmass_type\fP &mean_group_mass=1e14 *unitconv::Msuntokg *kg, const flt_type &sat_frac=0\&.2) const "
.br
.ti -1c
.RI "\fBsurface_density_type\fP \fBmodel_offset_Sigma\fP (const \fBmass_type\fP &mean_group_mass=1e14 *unitconv::Msuntokg *kg, const flt_type &sat_frac=0\&.2) const "
.br
.ti -1c
.RI "\fBpair_bin_summary\fP & \fBoperator+=\fP (const \fBpair_bin_summary\fP &other)"
.br
.ti -1c
.RI "\fBpair_bin_summary\fP \fBoperator+\fP (\fBpair_bin_summary\fP other) const "
.br
.ti -1c
.RI "void \fBsave\fP (std::ostream &) const "
.br
.ti -1c
.RI "void \fBsave\fP (const std::string &) const "
.br
.ti -1c
.RI "void \fBsave\fP (std::ostream &)"
.br
.ti -1c
.RI "void \fBsave\fP (const std::string &)"
.br
.ti -1c
.RI "void \fBload\fP (std::istream &)"
.br
.ti -1c
.RI "void \fBload\fP (const std::string &)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fB_uncache_values\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IceBRG::pair_bin_summary::pair_bin_summary (const \fBdistance_type\fP &init_R_min = \fC0\fP, const \fBdistance_type\fP &init_R_max = \fC0\fP, const \fBmass_type\fP &init_m_min = \fC0*\fBkg\fP\fP, const \fBmass_type\fP &init_m_max = \fC0*\fBkg\fP\fP, const \fBflt_type\fP &init_z_min = \fC0\fP, const \fBflt_type\fP &init_z_max = \fC0\fP, const \fBflt_type\fP &init_mag_min = \fC0\fP, const \fBflt_type\fP &init_mag_max = \fC0\fP)"

.SS "IceBRG::pair_bin_summary::pair_bin_summary (const \fBpair_bin\fP &bin)"

.SS "IceBRG::pair_bin_summary::pair_bin_summary (std::istream &in)"

.SS "IceBRG::pair_bin_summary::pair_bin_summary (std::string &filename)"

.SS "virtual IceBRG::pair_bin_summary::~pair_bin_summary ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void IceBRG::pair_bin_summary::_uncache_values ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual custom_unit_type<0,0,0,2,0> IceBRG::pair_bin_summary::area () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "custom_unit_type< 0, 0, 0, 2, 0 > IceBRG::pair_bin_summary::area_per_lens () const"

.SS "void IceBRG::pair_bin_summary::clear ()\fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual \fBsurface_density_type\fP IceBRG::pair_bin_summary::delta_Sigma_t_mean () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual custom_unit_type<-4,0,2,0,0> IceBRG::pair_bin_summary::delta_Sigma_t_mean_square () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "\fBsurface_density_type\fP IceBRG::pair_bin_summary::delta_Sigma_t_std () const\fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "\fBsurface_density_type\fP IceBRG::pair_bin_summary::delta_Sigma_t_stderr () const\fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual \fBsurface_density_type\fP IceBRG::pair_bin_summary::delta_Sigma_x_mean () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual custom_unit_type<-4,0,2,0,0> IceBRG::pair_bin_summary::delta_Sigma_x_mean_square () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "\fBsurface_density_type\fP IceBRG::pair_bin_summary::delta_Sigma_x_std () const\fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "\fBsurface_density_type\fP IceBRG::pair_bin_summary::delta_Sigma_x_stderr () const\fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin_summary::effective_pair_count () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "void IceBRG::pair_bin_summary::fixbad ()"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::gamma_mean () const"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::gamma_mean_square () const"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::gamma_square_stderr () const"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::gamma_stderr () const"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::gamma_t_mean () const"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::gamma_t_stderr () const"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::gamma_x_mean () const"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::gamma_x_stderr () const"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::kappa () const"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::kappa_stderr () const"

.SS "virtual \fBmass_type\fP IceBRG::pair_bin_summary::lens_m_mean () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin_summary::lens_mag_mean () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin_summary::lens_z_mean () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "void IceBRG::pair_bin_summary::load (std::istream &in)"

.SS "void IceBRG::pair_bin_summary::load (const std::string &filename)"

.SS "const \fBmass_type\fP& IceBRG::pair_bin_summary::m_max () const\fC [inline]\fP"

.SS "\fBmass_type\fP IceBRG::pair_bin_summary::m_mid () const\fC [inline]\fP"

.SS "const \fBmass_type\fP& IceBRG::pair_bin_summary::m_min () const\fC [inline]\fP"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::mag_max () const\fC [inline]\fP"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::mag_mid () const\fC [inline]\fP"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::mag_min () const\fC [inline]\fP"

.SS "virtual \fBflt_type\fP IceBRG::pair_bin_summary::magf_effective_num_lenses () const\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual \fBmass_type\fP IceBRG::pair_bin_summary::magf_lens_m_mean () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin_summary::magf_lens_mag_mean () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin_summary::magf_lens_z_mean () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual \fBssize_t\fP IceBRG::pair_bin_summary::magf_num_lenses () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual \fBssize_t\fP IceBRG::pair_bin_summary::magf_pair_count () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual \fBdistance_type\fP IceBRG::pair_bin_summary::magf_R_mean () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "\fBsurface_density_type\fP IceBRG::pair_bin_summary::magf_sigma_crit () const"

.SS "virtual \fBflt_type\fP IceBRG::pair_bin_summary::magf_source_z_mean () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin_summary::magf_sum_of_square_weights () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin_summary::magf_sum_of_weights () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "\fBsurface_density_type\fP IceBRG::pair_bin_summary::model_1h_delta_Sigma_t (const \fBflt_type\fP &MLratio_1h = \fC50\&.\fP) const"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::model_1h_gamma_t (const \fBflt_type\fP &MLratio_1h = \fC50\&.\fP) const"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::model_1h_kappa (const \fBflt_type\fP &MLratio_1h = \fC50\&.\fP) const"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::model_1h_mu (const \fBflt_type\fP &MLratio_1h = \fC50\&.\fP) const"

.SS "\fBsurface_density_type\fP IceBRG::pair_bin_summary::model_1h_Sigma (const \fBflt_type\fP &MLratio_1h = \fC50\&.\fP) const"

.SS "\fBsurface_density_type\fP IceBRG::pair_bin_summary::model_delta_Sigma_t (const \fBflt_type\fP &MLratio_1h = \fC50\&.\fP, const \fBmass_type\fP &mean_group_mass = \fC1e14*unitconv::Msuntokg*kg\fP, const \fBflt_type\fP &sat_frac = \fC0\&.2\fP) const"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::model_gamma_t (const \fBflt_type\fP &MLratio_1h = \fC50\&.\fP, const \fBmass_type\fP &mean_group_mass = \fC1e14*unitconv::Msuntokg*kg\fP, const \fBflt_type\fP &sat_frac = \fC0\&.2\fP) const"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::model_kappa (const \fBflt_type\fP &MLratio_1h = \fC50\&.\fP, const \fBmass_type\fP &mean_group_mass = \fC1e14*unitconv::Msuntokg*kg\fP, const \fBflt_type\fP &sat_frac = \fC0\&.2\fP) const"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::model_mu (const \fBflt_type\fP &MLratio_1h = \fC50\&.\fP, const \fBmass_type\fP &mean_group_mass = \fC1e14*unitconv::Msuntokg*kg\fP, const \fBflt_type\fP &sat_frac = \fC0\&.2\fP) const"

.SS "\fBsurface_density_type\fP IceBRG::pair_bin_summary::model_offset_delta_Sigma_t (const \fBmass_type\fP &mean_group_mass = \fC1e14*unitconv::Msuntokg*kg\fP, const \fBflt_type\fP &sat_frac = \fC0\&.2\fP) const"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::model_offset_gamma_t (const \fBmass_type\fP &mean_group_mass = \fC1e14*unitconv::Msuntokg*kg\fP, const \fBflt_type\fP &sat_frac = \fC0\&.2\fP) const"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::model_offset_kappa (const \fBmass_type\fP &mean_group_mass = \fC1e14*unitconv::Msuntokg*kg\fP, const \fBflt_type\fP &sat_frac = \fC0\&.2\fP) const"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::model_offset_mu (const \fBmass_type\fP &mean_group_mass = \fC1e14*unitconv::Msuntokg*kg\fP, const \fBflt_type\fP &sat_frac = \fC0\&.2\fP) const"

.SS "\fBsurface_density_type\fP IceBRG::pair_bin_summary::model_offset_Sigma (const \fBmass_type\fP &mean_group_mass = \fC1e14*unitconv::Msuntokg*kg\fP, const \fBflt_type\fP &sat_frac = \fC0\&.2\fP) const"

.SS "\fBsurface_density_type\fP IceBRG::pair_bin_summary::model_Sigma (const \fBflt_type\fP &MLratio_1h = \fC50\&.\fP, const \fBmass_type\fP &mean_group_mass = \fC1e14*unitconv::Msuntokg*kg\fP, const \fBflt_type\fP &sat_frac = \fC0\&.2\fP) const"

.SS "virtual \fBflt_type\fP IceBRG::pair_bin_summary::mu_hat () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin_summary::mu_square_hat () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "\fBflt_type\fP IceBRG::pair_bin_summary::mu_std () const"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::mu_stderr () const"

.SS "virtual \fBflt_type\fP IceBRG::pair_bin_summary::mu_W () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual \fBssize_t\fP IceBRG::pair_bin_summary::num_lenses () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "\fBpair_bin_summary\fP IceBRG::pair_bin_summary::operator+ (\fBpair_bin_summary\fPother) const\fC [inline]\fP"

.SS "\fBpair_bin_summary\fP & IceBRG::pair_bin_summary::operator+= (const \fBpair_bin_summary\fP &other)"

.SS "\fBpair_bin_summary\fP& IceBRG::pair_bin_summary::operator= (const \fBpair_bin\fP &bin)\fC [inline]\fP"

.SS "virtual \fBssize_t\fP IceBRG::pair_bin_summary::pair_count () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "\fBdistance_type\fP IceBRG::pair_bin_summary::R_amid () const\fC [inline]\fP"

.SS "const \fBdistance_type\fP& IceBRG::pair_bin_summary::R_max () const\fC [inline]\fP"

.SS "virtual \fBdistance_type\fP IceBRG::pair_bin_summary::R_mean () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "\fBdistance_type\fP IceBRG::pair_bin_summary::R_mid () const\fC [inline]\fP"

.SS "const \fBdistance_type\fP& IceBRG::pair_bin_summary::R_min () const\fC [inline]\fP"

.SS "void IceBRG::pair_bin_summary::save (std::ostream &out) const"

.SS "void IceBRG::pair_bin_summary::save (const std::string &filename) const"

.SS "void IceBRG::pair_bin_summary::save (std::ostream &out)"

.SS "void IceBRG::pair_bin_summary::save (const std::string &filename)"

.SS "template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 > void IceBRG::pair_bin_summary::set_limits (T1 &&R_min, T2 &&R_max, T3 &&m_min, T4 &&m_max, T5 &&z_min, T6 &&z_max, T7 &&mag_min, T8 &&mag_max)\fC [inline]\fP"

.SS "template<typename T1 , typename T2 > void IceBRG::pair_bin_summary::set_m_limits (T1 &&m_min, T2 &&m_max)\fC [inline]\fP"

.SS "template<typename T1 , typename T2 > void IceBRG::pair_bin_summary::set_mag_limits (T1 &&mag_min, T2 &&mag_max)\fC [inline]\fP"

.SS "template<typename T1 , typename T2 > void IceBRG::pair_bin_summary::set_R_limits (T1 &&R_min, T2 &&R_max)\fC [inline]\fP"

.SS "template<typename T1 , typename T2 > void IceBRG::pair_bin_summary::set_z_limits (T1 &&z_min, T2 &&z_max)\fC [inline]\fP"

.SS "virtual \fBflt_type\fP IceBRG::pair_bin_summary::shear_effective_pair_count () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual \fBmass_type\fP IceBRG::pair_bin_summary::shear_lens_m_mean () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin_summary::shear_lens_mag_mean () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin_summary::shear_lens_z_mean () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual \fBssize_t\fP IceBRG::pair_bin_summary::shear_pair_count () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual \fBdistance_type\fP IceBRG::pair_bin_summary::shear_R_mean () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "\fBsurface_density_type\fP IceBRG::pair_bin_summary::shear_sigma_crit () const"

.SS "virtual \fBflt_type\fP IceBRG::pair_bin_summary::shear_source_z_mean () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin_summary::shear_sum_of_square_weights () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin_summary::shear_sum_of_weights () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "\fBsurface_density_type\fP IceBRG::pair_bin_summary::Sigma () const"

.SS "\fBsurface_density_type\fP IceBRG::pair_bin_summary::Sigma_stderr () const"

.SS "virtual \fBflt_type\fP IceBRG::pair_bin_summary::source_z_mean () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin_summary::sum_of_square_weights () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin_summary::sum_of_weights () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBIceBRG::pair_bin\fP\&.
.SS "\fBflt_type\fP IceBRG::pair_bin_summary::z_max () const\fC [inline]\fP"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::z_mid () const\fC [inline]\fP"

.SS "\fBflt_type\fP IceBRG::pair_bin_summary::z_min () const\fC [inline]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class boost::serialization::access\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
