.TH "IceBRG::mag_expected_count_functor" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IceBRG::mag_expected_count_functor \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <magnification_functors\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmag_expected_count_functor\fP (\fBflt_type\fP init_z=0)"
.br
.ti -1c
.RI "virtual \fB~mag_expected_count_functor\fP ()"
.br
.ti -1c
.RI "\fBflt_type\fP \fBoperator()\fP (const \fBlong_flt_type\fP &\fBm\fP=true) const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IceBRG::mag_expected_count_functor::mag_expected_count_functor (\fBflt_type\fPinit_z = \fC0\fP)\fC [inline]\fP"

.SS "virtual IceBRG::mag_expected_count_functor::~mag_expected_count_functor ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBflt_type\fP IceBRG::mag_expected_count_functor::operator() (const \fBlong_flt_type\fP &m = \fCtrue\fP) const"


.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
