.TH "IceBRG::shifting_loader" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IceBRG::shifting_loader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shifting_loader\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBflt_type\fP \fBget\fP (\fBflt_type\fP theta, \fBflt_type\fP z)"
.br
.ti -1c
.RI "void \fBunload\fP ()"
.br
.ti -1c
.RI "\fBshifting_loader\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IceBRG::shifting_loader::shifting_loader ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBflt_type\fP IceBRG::shifting_loader::get (\fBflt_type\fPtheta, \fBflt_type\fPz)"

.SS "void IceBRG::shifting_loader::unload ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
