.TH "IceBRG::expected_count_cache" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IceBRG::expected_count_cache \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <expected_count_cache\&.h>\fP
.PP
Inherits \fBIceBRG::brg_cache_2d< name >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexpected_count_cache\fP ()"
.br
.ti -1c
.RI "\fB~expected_count_cache\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "std::string \fB_name_base\fP () const "
.br
.ti -1c
.RI "\fBflt_type\fP \fB_calculate\fP (const \fBflt_type\fP &in_param_1, const \fBflt_type\fP &in_param_2) const "
.br
.ti -1c
.RI "void \fB_load_cache_dependencies\fP () const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBbrg_cache_2d< expected_count_cache >\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IceBRG::expected_count_cache::expected_count_cache ()\fC [inline]\fP"

.SS "IceBRG::expected_count_cache::~expected_count_cache ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBflt_type\fP IceBRG::expected_count_cache::_calculate (const \fBflt_type\fP &in_param_1, const \fBflt_type\fP &in_param_2) const\fC [protected]\fP"

.PP
Reimplemented from \fBIceBRG::brg_cache_2d< name >\fP\&.
.SS "void IceBRG::expected_count_cache::_load_cache_dependencies () const\fC [protected]\fP"

.PP
Reimplemented from \fBIceBRG::brg_cache_2d< name >\fP\&.
.SS "std::string IceBRG::expected_count_cache::_name_base () const\fC [inline]\fP, \fC [protected]\fP"

.PP
Reimplemented from \fBIceBRG::brg_cache_2d< name >\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBbrg_cache_2d\fP< \fBexpected_count_cache\fP >\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
