.TH "IceBRG::mu_signal_integration_functor" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IceBRG::mu_signal_integration_functor \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <magnification_functors\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmu_signal_integration_functor\fP (\fBflt_type\fP init_z=0)"
.br
.ti -1c
.RI "virtual \fB~mu_signal_integration_functor\fP ()"
.br
.ti -1c
.RI "\fBflt_type\fP \fBoperator()\fP (const \fBlong_flt_type\fP &\fBm\fP=true) const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IceBRG::mu_signal_integration_functor::mu_signal_integration_functor (\fBflt_type\fPinit_z = \fC0\fP)\fC [inline]\fP"

.SS "virtual IceBRG::mu_signal_integration_functor::~mu_signal_integration_functor ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBflt_type\fP IceBRG::mu_signal_integration_functor::operator() (const \fBlong_flt_type\fP &m = \fCtrue\fP) const"


.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
