.TH "IceBRG::projected_density_functor< name >" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IceBRG::projected_density_functor< name > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lensing_profile_extension_functors\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBset_host_ptr\fP (const name *new_host_ptr)"
.br
.ti -1c
.RI "const name * \fBhost_ptr\fP ()"
.br
.ti -1c
.RI "void \fBset_offset_R\fP (const \fBdistance_type\fP &new_offset_R)"
.br
.ti -1c
.RI "const \fBdistance_type\fP \fBoffset_R\fP ()"
.br
.ti -1c
.RI "\fBsurface_density_type\fP \fBoperator()\fP (const \fBdistance_type\fP &in_param) const "
.br
.ti -1c
.RI "\fBprojected_density_functor\fP (const name *init_host=\fBNULL\fP, const \fBdistance_type\fP &init_offset_R=0)"
.br
.ti -1c
.RI "virtual \fB~projected_density_functor\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename name> \fBIceBRG::projected_density_functor\fP< name >::\fBprojected_density_functor\fP (const name *init_host = \fC\fBNULL\fP\fP, const \fBdistance_type\fP &init_offset_R = \fC0\fP)\fC [inline]\fP"

.SS "template<typename name> virtual \fBIceBRG::projected_density_functor\fP< name >::~\fBprojected_density_functor\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename name> const name* \fBIceBRG::projected_density_functor\fP< name >::host_ptr ()\fC [inline]\fP"

.SS "template<typename name> const \fBdistance_type\fP \fBIceBRG::projected_density_functor\fP< name >::offset_R ()\fC [inline]\fP"

.SS "template<typename name> \fBsurface_density_type\fP \fBIceBRG::projected_density_functor\fP< name >::operator() (const \fBdistance_type\fP &in_param) const\fC [inline]\fP"

.SS "template<typename name> void \fBIceBRG::projected_density_functor\fP< name >::set_host_ptr (const name *new_host_ptr)\fC [inline]\fP"

.SS "template<typename name> void \fBIceBRG::projected_density_functor\fP< name >::set_offset_R (const \fBdistance_type\fP &new_offset_R)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
