.TH "IceBRG::mag_weight_integral_cache" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IceBRG::mag_weight_integral_cache \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mag_weight_integral_cache\&.h>\fP
.PP
Inherits \fBIceBRG::brg_cache< mag_weight_integral_cache >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmag_weight_integral_cache\fP ()"
.br
.ti -1c
.RI "\fB~mag_weight_integral_cache\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "std::string \fB_name_base\fP () const "
.br
.ti -1c
.RI "\fBflt_type\fP \fB_calculate\fP (const \fBflt_type\fP &in_param_1) const "
.br
.ti -1c
.RI "void \fB_load_cache_dependencies\fP () const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBbrg_cache< mag_weight_integral_cache >\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IceBRG::mag_weight_integral_cache::mag_weight_integral_cache ()\fC [inline]\fP"

.SS "IceBRG::mag_weight_integral_cache::~mag_weight_integral_cache ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBflt_type\fP IceBRG::mag_weight_integral_cache::_calculate (const \fBflt_type\fP &in_param_1) const\fC [protected]\fP"

.PP
Reimplemented from \fBIceBRG::brg_cache< mag_weight_integral_cache >\fP\&.
.SS "void IceBRG::mag_weight_integral_cache::_load_cache_dependencies () const\fC [protected]\fP"

.PP
Reimplemented from \fBIceBRG::brg_cache< mag_weight_integral_cache >\fP\&.
.SS "std::string IceBRG::mag_weight_integral_cache::_name_base () const\fC [inline]\fP, \fC [protected]\fP"

.PP
Reimplemented from \fBIceBRG::brg_cache< mag_weight_integral_cache >\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBbrg_cache\fP< \fBmag_weight_integral_cache\fP >\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
