.TH "IceBRG::tNFW_offset_sig_cache" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IceBRG::tNFW_offset_sig_cache \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lensing_tNFW_caches\&.h>\fP
.PP
Inherits \fBIceBRG::brg_cache_4d< tNFW_offset_sig_cache >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~tNFW_offset_sig_cache\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "const std::string \fB_name_base\fP () const "
.br
.ti -1c
.RI "\fBflt_type\fP \fB_calculate\fP (const \fBflt_type\fP &in_param_1, const \fBflt_type\fP &in_param_2, const \fBflt_type\fP &in_param_3, const \fBflt_type\fP &in_param_4) const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBbrg_cache_4d< tNFW_offset_sig_cache >\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IceBRG::tNFW_offset_sig_cache::~tNFW_offset_sig_cache ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBflt_type\fP IceBRG::tNFW_offset_sig_cache::_calculate (const \fBflt_type\fP &in_param_1, const \fBflt_type\fP &in_param_2, const \fBflt_type\fP &in_param_3, const \fBflt_type\fP &in_param_4) const\fC [protected]\fP"

.PP
Reimplemented from \fBIceBRG::brg_cache_4d< tNFW_offset_sig_cache >\fP\&.
.SS "const std::string IceBRG::tNFW_offset_sig_cache::_name_base () const\fC [inline]\fP, \fC [protected]\fP"

.PP
Reimplemented from \fBIceBRG::brg_cache_4d< tNFW_offset_sig_cache >\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBbrg_cache_4d\fP< \fBtNFW_offset_sig_cache\fP >\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
