.TH "IceBRG::shifted_Delta_Sigma_weight_functor< name >" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IceBRG::shifted_Delta_Sigma_weight_functor< name > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lensing_profile_extension_functors\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBset_sigma\fP (const \fBdistance_type\fP &new_sigma)"
.br
.ti -1c
.RI "const \fBdistance_type\fP & \fBsigma\fP ()"
.br
.ti -1c
.RI "\fBflt_type\fP \fBoperator()\fP (const \fBdistance_type\fP &in_param) const "
.br
.ti -1c
.RI "\fBshifted_Delta_Sigma_weight_functor\fP (const \fBdistance_type\fP &new_sigma=0)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename name> \fBIceBRG::shifted_Delta_Sigma_weight_functor\fP< name >::\fBshifted_Delta_Sigma_weight_functor\fP (const \fBdistance_type\fP &new_sigma = \fC0\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename name> \fBflt_type\fP \fBIceBRG::shifted_Delta_Sigma_weight_functor\fP< name >::operator() (const \fBdistance_type\fP &in_param) const\fC [inline]\fP"

.SS "template<typename name> void \fBIceBRG::shifted_Delta_Sigma_weight_functor\fP< name >::set_sigma (const \fBdistance_type\fP &new_sigma)\fC [inline]\fP"

.SS "template<typename name> const \fBdistance_type\fP& \fBIceBRG::shifted_Delta_Sigma_weight_functor\fP< name >::sigma ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
