.TH "IceBRG::lens_id" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IceBRG::lens_id \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pair_bin\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBflt_type\fP \fBunmasked_frac\fP (const \fBdistance_type\fP &R_proj) const "
.br
.ti -1c
.RI "\fBlens_id\fP (const \fBssize_t\fP &\fBid\fP, const \fBmass_type\fP &\fBm\fP, const \fBflt_type\fP &\fBz\fP, const \fBflt_type\fP &\fBmag\fP, const std::vector< \fBdistance_type\fP > &\fBunmasked_frac_bin_limits\fP, const std::vector< \fBflt_type\fP > &\fBunmasked_fracs\fP, const \fBflt_type\fP &\fBweight\fP=1)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBssize_t\fP \fBid\fP"
.br
.ti -1c
.RI "\fBmass_type\fP \fBm\fP"
.br
.ti -1c
.RI "\fBflt_type\fP \fBz\fP"
.br
.ti -1c
.RI "\fBflt_type\fP \fBmag\fP"
.br
.ti -1c
.RI "\fBflt_type\fP \fBweight\fP"
.br
.ti -1c
.RI "\fBIceBRG::limit_vector\fP
.br
< \fBdistance_type\fP > \fBunmasked_frac_bin_limits\fP"
.br
.ti -1c
.RI "std::vector< \fBflt_type\fP > \fBunmasked_fracs\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IceBRG::lens_id::lens_id (const \fBssize_t\fP &id, const \fBmass_type\fP &m, const \fBflt_type\fP &z, const \fBflt_type\fP &mag, const std::vector< \fBdistance_type\fP > &unmasked_frac_bin_limits, const std::vector< \fBflt_type\fP > &unmasked_fracs, const \fBflt_type\fP &weight = \fC1\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBflt_type\fP IceBRG::lens_id::unmasked_frac (const \fBdistance_type\fP &R_proj) const"

.SH "Field Documentation"
.PP 
.SS "\fBssize_t\fP IceBRG::lens_id::id"

.SS "\fBmass_type\fP IceBRG::lens_id::m"

.SS "\fBflt_type\fP IceBRG::lens_id::mag"

.SS "\fBIceBRG::limit_vector\fP<\fBdistance_type\fP> IceBRG::lens_id::unmasked_frac_bin_limits"

.SS "std::vector<\fBflt_type\fP> IceBRG::lens_id::unmasked_fracs"

.SS "\fBflt_type\fP IceBRG::lens_id::weight"

.SS "\fBflt_type\fP IceBRG::lens_id::z"


.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
