.TH "IceBRG::expected_count_loader" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IceBRG::expected_count_loader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <expected_count_loader\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_z_limits\fP (const std::vector< \fBflt_type\fP > &new_limits_vector)"
.br
.ti -1c
.RI "static void \fBset_z_limits\fP (std::vector< \fBflt_type\fP > &&new_limits_vector)"
.br
.ti -1c
.RI "static void \fBset_filename_base\fP (const std::string &new_filename_base)"
.br
.ti -1c
.RI "static void \fBset_filename_base\fP (std::string &&new_filename_base)"
.br
.ti -1c
.RI "static void \fBset_filename_tail\fP (const std::string &new_filename_tail)"
.br
.ti -1c
.RI "static void \fBset_filename_tail\fP (std::string &&new_filename_tail)"
.br
.ti -1c
.RI "static \fBflt_type\fP \fBget_count\fP (const \fBflt_type\fP &mag, const \fBflt_type\fP &z)"
.br
.ti -1c
.RI "static \fBflt_type\fP \fBget_derivative\fP (const \fBflt_type\fP &mag, const \fBflt_type\fP &z)"
.br
.ti -1c
.RI "static void \fBunload\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBflt_type\fP IceBRG::expected_count_loader::get_count (const \fBflt_type\fP &mag, const \fBflt_type\fP &z)\fC [static]\fP"

.SS "\fBflt_type\fP IceBRG::expected_count_loader::get_derivative (const \fBflt_type\fP &mag, const \fBflt_type\fP &z)\fC [static]\fP"

.SS "void IceBRG::expected_count_loader::set_filename_base (const std::string &new_filename_base)\fC [static]\fP"

.SS "void IceBRG::expected_count_loader::set_filename_base (std::string &&new_filename_base)\fC [static]\fP"

.SS "void IceBRG::expected_count_loader::set_filename_tail (const std::string &new_filename_tail)\fC [static]\fP"

.SS "void IceBRG::expected_count_loader::set_filename_tail (std::string &&new_filename_tail)\fC [static]\fP"

.SS "void IceBRG::expected_count_loader::set_z_limits (const std::vector< \fBflt_type\fP > &new_limits_vector)\fC [static]\fP"

.SS "void IceBRG::expected_count_loader::set_z_limits (std::vector< \fBflt_type\fP > &&new_limits_vector)\fC [static]\fP"

.SS "static void IceBRG::expected_count_loader::unload ()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
