.TH "IceBRG::group_Delta_Sigma_weight_functor< name >" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IceBRG::group_Delta_Sigma_weight_functor< name > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lensing_profile_extension_functors\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBset_host_ptr\fP (const name *new_host_ptr)"
.br
.ti -1c
.RI "const name * \fBhost_ptr\fP ()"
.br
.ti -1c
.RI "void \fBset_c\fP (const \fBflt_type\fP &new_c)"
.br
.ti -1c
.RI "const \fBflt_type\fP & \fBc\fP () noexcept"
.br
.ti -1c
.RI "\fBflt_type\fP \fBoperator()\fP (const \fBdistance_type\fP &in_param) const "
.br
.ti -1c
.RI "\fBgroup_Delta_Sigma_weight_functor\fP (const name *init_host=\fBNULL\fP, const \fBflt_type\fP &init_c=-1)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename name> \fBIceBRG::group_Delta_Sigma_weight_functor\fP< name >::\fBgroup_Delta_Sigma_weight_functor\fP (const name *init_host = \fC\fBNULL\fP\fP, const \fBflt_type\fP &init_c = \fC-1\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename name> const \fBflt_type\fP& \fBIceBRG::group_Delta_Sigma_weight_functor\fP< name >::c ()\fC [inline]\fP"

.SS "template<typename name> const name* \fBIceBRG::group_Delta_Sigma_weight_functor\fP< name >::host_ptr ()\fC [inline]\fP"

.SS "template<typename name> \fBflt_type\fP \fBIceBRG::group_Delta_Sigma_weight_functor\fP< name >::operator() (const \fBdistance_type\fP &in_param) const\fC [inline]\fP"

.SS "template<typename name> void \fBIceBRG::group_Delta_Sigma_weight_functor\fP< name >::set_c (const \fBflt_type\fP &new_c)\fC [inline]\fP"

.SS "template<typename name> void \fBIceBRG::group_Delta_Sigma_weight_functor\fP< name >::set_host_ptr (const name *new_host_ptr)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
