.TH "IceBRG::mag_calibration_loader" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IceBRG::mag_calibration_loader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mag_calibration_loader\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_z_mins\fP (const std::vector< \fBflt_type\fP > &new_limits_vector)"
.br
.ti -1c
.RI "static void \fBset_z_mins\fP (std::vector< \fBflt_type\fP > &&new_limits_vector)"
.br
.ti -1c
.RI "static void \fBset_filename\fP (const std::string &new_filename)"
.br
.ti -1c
.RI "static void \fBset_filename\fP (std::string &&new_filename)"
.br
.ti -1c
.RI "static \fBflt_type\fP \fBget\fP (const \fBflt_type\fP &z)"
.br
.ti -1c
.RI "static void \fBunload\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBflt_type\fP IceBRG::mag_calibration_loader::get (const \fBflt_type\fP &z)\fC [static]\fP"

.SS "void IceBRG::mag_calibration_loader::set_filename (const std::string &new_filename)\fC [static]\fP"

.SS "void IceBRG::mag_calibration_loader::set_filename (std::string &&new_filename)\fC [static]\fP"

.SS "void IceBRG::mag_calibration_loader::set_z_mins (const std::vector< \fBflt_type\fP > &new_limits_vector)\fC [static]\fP"

.SS "void IceBRG::mag_calibration_loader::set_z_mins (std::vector< \fBflt_type\fP > &&new_limits_vector)\fC [static]\fP"

.SS "void IceBRG::mag_calibration_loader::unload ()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
