.TH "IceBRG::pair_bin" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IceBRG::pair_bin \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pair_bin\&.h>\fP
.PP
Inherits \fBIceBRG::pair_bin_summary\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpair_bin\fP (const \fBdistance_type\fP &init_R_min=0, const \fBdistance_type\fP &init_R_max=0, const \fBmass_type\fP &init_m_min=0, const \fBmass_type\fP &init_m_max=0, const \fBflt_type\fP &init_z_min=0, const \fBflt_type\fP &init_z_max=0, const \fBflt_type\fP &init_mag_min=0, const \fBflt_type\fP &init_mag_max=0, const \fBflt_type\fP &init_z_buffer=_z_buffer_default_value_)"
.br
.ti -1c
.RI "virtual \fB~pair_bin\fP ()"
.br
.ti -1c
.RI "void \fBset_z_buffer\fP (const \fBflt_type\fP &new_z_buffer)"
.br
.ti -1c
.RI "\fBflt_type\fP \fBz_buffer\fP () const "
.br
.ti -1c
.RI "void \fBadd_pair\fP (const \fBlens_source_pair\fP &new_pair)"
.br
.ti -1c
.RI "void \fBadd_lens\fP (const \fBlens_id\fP &lens)"
.br
.ti -1c
.RI "virtual void \fBclear\fP () override"
.br
.ti -1c
.RI "virtual \fBssize_t\fP \fBpair_count\fP () const override"
.br
.ti -1c
.RI "virtual \fBssize_t\fP \fBshear_pair_count\fP () const override"
.br
.ti -1c
.RI "virtual \fBssize_t\fP \fBmagf_pair_count\fP () const override"
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBeffective_pair_count\fP () const override"
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBshear_effective_pair_count\fP () const override"
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBsum_of_weights\fP () const override"
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBshear_sum_of_weights\fP () const override"
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBmagf_sum_of_weights\fP () const override"
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBsum_of_square_weights\fP () const override"
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBshear_sum_of_square_weights\fP () const override"
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBmagf_sum_of_square_weights\fP () const override"
.br
.ti -1c
.RI "virtual \fBssize_t\fP \fBnum_lenses\fP () const override"
.br
.ti -1c
.RI "virtual \fBssize_t\fP \fBmagf_num_lenses\fP () const override"
.br
.ti -1c
.RI "virtual \fBdistance_type\fP \fBR_mean\fP () const override"
.br
.ti -1c
.RI "virtual \fBdistance_type\fP \fBshear_R_mean\fP () const override"
.br
.ti -1c
.RI "virtual \fBdistance_type\fP \fBmagf_R_mean\fP () const override"
.br
.ti -1c
.RI "virtual \fBmass_type\fP \fBlens_m_mean\fP () const override"
.br
.ti -1c
.RI "virtual \fBmass_type\fP \fBshear_lens_m_mean\fP () const override"
.br
.ti -1c
.RI "virtual \fBmass_type\fP \fBmagf_lens_m_mean\fP () const override"
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBlens_z_mean\fP () const override"
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBshear_lens_z_mean\fP () const override"
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBmagf_lens_z_mean\fP () const override"
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBlens_mag_mean\fP () const override"
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBshear_lens_mag_mean\fP () const override"
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBmagf_lens_mag_mean\fP () const override"
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBsource_z_mean\fP () const override"
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBshear_source_z_mean\fP () const override"
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBmagf_source_z_mean\fP () const override"
.br
.ti -1c
.RI "\fBflt_type\fP \fBunmasked_frac\fP () const "
.br
.ti -1c
.RI "virtual custom_unit_type< 0, 0, 0, 2, 0 > \fBarea\fP () const override"
.br
.ti -1c
.RI "virtual \fBsurface_density_type\fP \fBdelta_Sigma_t_mean\fP () const override"
.br
.ti -1c
.RI "virtual \fBsurface_density_type\fP \fBdelta_Sigma_x_mean\fP () const override"
.br
.ti -1c
.RI "virtual custom_unit_type<-4, 0, 2, 0, 0 > \fBdelta_Sigma_t_mean_square\fP () const override"
.br
.ti -1c
.RI "virtual custom_unit_type<-4, 0, 2, 0, 0 > \fBdelta_Sigma_x_mean_square\fP () const override"
.br
.ti -1c
.RI "virtual \fBsurface_density_type\fP \fBdelta_Sigma_t_std\fP () const override"
.br
.ti -1c
.RI "virtual \fBsurface_density_type\fP \fBdelta_Sigma_x_std\fP () const override"
.br
.ti -1c
.RI "virtual \fBsurface_density_type\fP \fBdelta_Sigma_t_stderr\fP () const override"
.br
.ti -1c
.RI "virtual \fBsurface_density_type\fP \fBdelta_Sigma_x_stderr\fP () const override"
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBmu_hat\fP () const override"
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBmu_square_hat\fP () const override"
.br
.ti -1c
.RI "virtual \fBflt_type\fP \fBmu_W\fP () const override"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fB_uncache_values\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IceBRG::pair_bin::pair_bin (const \fBdistance_type\fP &init_R_min = \fC0\fP, const \fBdistance_type\fP &init_R_max = \fC0\fP, const \fBmass_type\fP &init_m_min = \fC0\fP, const \fBmass_type\fP &init_m_max = \fC0\fP, const \fBflt_type\fP &init_z_min = \fC0\fP, const \fBflt_type\fP &init_z_max = \fC0\fP, const \fBflt_type\fP &init_mag_min = \fC0\fP, const \fBflt_type\fP &init_mag_max = \fC0\fP, const \fBflt_type\fP &init_z_buffer = \fC_z_buffer_default_value_\fP)"

.SS "virtual IceBRG::pair_bin::~pair_bin ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void IceBRG::pair_bin::_uncache_values ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "void IceBRG::pair_bin::add_lens (const \fBlens_id\fP &lens)"

.SS "void IceBRG::pair_bin::add_pair (const \fBlens_source_pair\fP &new_pair)"

.SS "custom_unit_type< 0, 0, 0, 2, 0 > IceBRG::pair_bin::area () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "void IceBRG::pair_bin::clear ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "\fBsurface_density_type\fP IceBRG::pair_bin::delta_Sigma_t_mean () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "custom_unit_type<-4, 0, 2, 0, 0 > IceBRG::pair_bin::delta_Sigma_t_mean_square () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "\fBsurface_density_type\fP IceBRG::pair_bin::delta_Sigma_t_std () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "\fBsurface_density_type\fP IceBRG::pair_bin::delta_Sigma_t_stderr () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "\fBsurface_density_type\fP IceBRG::pair_bin::delta_Sigma_x_mean () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "custom_unit_type<-4, 0, 2, 0, 0 > IceBRG::pair_bin::delta_Sigma_x_mean_square () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "\fBsurface_density_type\fP IceBRG::pair_bin::delta_Sigma_x_std () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "\fBsurface_density_type\fP IceBRG::pair_bin::delta_Sigma_x_stderr () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin::effective_pair_count () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBmass_type\fP IceBRG::pair_bin::lens_m_mean () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin::lens_mag_mean () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin::lens_z_mean () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBmass_type\fP IceBRG::pair_bin::magf_lens_m_mean () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin::magf_lens_mag_mean () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin::magf_lens_z_mean () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBssize_t\fP IceBRG::pair_bin::magf_num_lenses () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBssize_t\fP IceBRG::pair_bin::magf_pair_count () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBdistance_type\fP IceBRG::pair_bin::magf_R_mean () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin::magf_source_z_mean () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "\fBflt_type\fP IceBRG::pair_bin::magf_sum_of_square_weights () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "\fBflt_type\fP IceBRG::pair_bin::magf_sum_of_weights () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "\fBflt_type\fP IceBRG::pair_bin::mu_hat () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "\fBflt_type\fP IceBRG::pair_bin::mu_square_hat () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "\fBflt_type\fP IceBRG::pair_bin::mu_W () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBssize_t\fP IceBRG::pair_bin::num_lenses () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBssize_t\fP IceBRG::pair_bin::pair_count () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBdistance_type\fP IceBRG::pair_bin::R_mean () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "void IceBRG::pair_bin::set_z_buffer (const \fBflt_type\fP &new_z_buffer)\fC [inline]\fP"

.SS "virtual \fBflt_type\fP IceBRG::pair_bin::shear_effective_pair_count () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBmass_type\fP IceBRG::pair_bin::shear_lens_m_mean () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin::shear_lens_mag_mean () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin::shear_lens_z_mean () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBssize_t\fP IceBRG::pair_bin::shear_pair_count () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBdistance_type\fP IceBRG::pair_bin::shear_R_mean () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin::shear_source_z_mean () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin::shear_sum_of_square_weights () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin::shear_sum_of_weights () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin::source_z_mean () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin::sum_of_square_weights () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "virtual \fBflt_type\fP IceBRG::pair_bin::sum_of_weights () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::pair_bin_summary\fP\&.
.SS "\fBflt_type\fP IceBRG::pair_bin::unmasked_frac () const\fC [inline]\fP"

.SS "\fBflt_type\fP IceBRG::pair_bin::z_buffer () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
