.TH "IceBRG::lensing_tNFW_profile" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IceBRG::lensing_tNFW_profile \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lensing_tNFW_profile\&.h>\fP
.PP
Inherits \fBIceBRG::tNFW_profile\fP, and \fBIceBRG::lensing_profile_extension< lensing_tNFW_profile >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlensing_tNFW_profile\fP ()"
.br
.ti -1c
.RI "\fBlensing_tNFW_profile\fP (const \fBmass_type\fP &init_mvir0, const \fBflt_type\fP &init_z, const \fBflt_type\fP &init_c=-1, const \fBflt_type\fP &init_tau=-1)"
.br
.ti -1c
.RI "virtual \fB~lensing_tNFW_profile\fP ()"
.br
.ti -1c
.RI "virtual \fBdensity_profile\fP * \fBdensity_profile_clone\fP () const "
.br
.ti -1c
.RI "virtual \fBtNFW_profile\fP * \fBtNFW_profile_clone\fP () const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBlensing_profile_extension< lensing_tNFW_profile >\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IceBRG::lensing_tNFW_profile::lensing_tNFW_profile ()\fC [inline]\fP"

.SS "IceBRG::lensing_tNFW_profile::lensing_tNFW_profile (const \fBmass_type\fP &init_mvir0, const \fBflt_type\fP &init_z, const \fBflt_type\fP &init_c = \fC-1\fP, const \fBflt_type\fP &init_tau = \fC-1\fP)\fC [inline]\fP"

.SS "virtual IceBRG::lensing_tNFW_profile::~lensing_tNFW_profile ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBdensity_profile\fP* IceBRG::lensing_tNFW_profile::density_profile_clone () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::tNFW_profile\fP\&.
.SS "virtual \fBtNFW_profile\fP* IceBRG::lensing_tNFW_profile::tNFW_profile_clone () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIceBRG::tNFW_profile\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBlensing_profile_extension\fP< \fBlensing_tNFW_profile\fP >\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
