.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/math/interpolator/interpolator_derivative.cpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/math/interpolator/interpolator_derivative.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <utility>\fP
.br
\fC#include 'IceBRG_main/math/calculus/differentiate\&.hpp'\fP
.br
\fC#include 'IceBRG_main/math/calculus/integrate\&.hpp'\fP
.br
\fC#include 'IceBRG_main/math/random/distributions\&.hpp'\fP
.br
\fC#include 'IceBRG_main/utility\&.hpp'\fP
.br
\fC#include 'interpolator_derivative\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "template<> void \fBstd::swap\fP (\fBIceBRG::interpolator_derivative\fP &same, \fBIceBRG::interpolator_derivative\fP &other)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
