.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/math/interpolator/interpolator.h" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/math/interpolator/interpolator.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include 'IceBRG_main/common\&.h'\fP
.br
\fC#include 'IceBRG_main/utility\&.hpp'\fP
.br
\fC#include 'IceBRG_main/external/tk_spline\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBIceBRG::interpolator\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBIceBRG::p1first_lt_p2first\fP (std::pair< \fBflt_type\fP, \fBflt_type\fP > pair1, std::pair< \fBflt_type\fP, \fBflt_type\fP > pair2)"
.br
.ti -1c
.RI "bool \fBIceBRG::p1first_lt_v2\fP (std::pair< \fBflt_type\fP, \fBflt_type\fP > pair1, \fBflt_type\fP v2)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
