.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/math/ipow.hpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/math/ipow.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <type_traits>\fP
.br
\fC#include '\&.\&./container/is_stl_container\&.hpp'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBIceBRG::_ipow_s< p >\fP"
.br
.ti -1c
.RI "struct \fBIceBRG::_ipow_s< 1 >\fP"
.br
.ti -1c
.RI "struct \fBIceBRG::_ipow_s< 0 >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , typename std::enable_if<!IceBRG::is_stl_container< T >::value, T >::type *  = nullptr> T \fBIceBRG::_runtime_ipow\fP (T v, \fBint_type\fP p)"
.br
.ti -1c
.RI "template<typename T , typename std::enable_if<!IceBRG::is_stl_container< T >::value, T >::type *  = nullptr> T \fBIceBRG::runtime_ipow\fP (T v, \fBint_type\fP p)"
.br
.ti -1c
.RI "template<int_type p> \fBflt_type\fP \fBIceBRG::ipow\fP (const \fBflt_type\fP &v)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
