.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/container/is_eigen_container.hpp" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/container/is_eigen_container.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <type_traits>\fP
.br
\fC#include 'IceBRG_main/Eigen\&.hpp'\fP
.br
\fC#include 'is_stl_container\&.hpp'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBIceBRG::is_eigen_container< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.in -1c
.SH "Data Structure Documentation"
.PP 
.SH "struct IceBRG::is_eigen_container"
.PP 

.SS "template<typename T>struct IceBRG::is_eigen_container< T >"

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
