.TH "/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_get_unmasked_fractions/is_good_position.hpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_get_unmasked_fractions/is_good_position.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBis_good_position\fP (int i, int j, const std::vector< std::vector< bool >> &vec)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool is_good_position (inti, intj, const std::vector< std::vector< bool >> &vec)\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
