.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/join_path.hpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/join_path.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <boost/algorithm/string/replace\&.hpp>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBIceBRG::reduce_slashes\fP (std::string &s)"
.br
.ti -1c
.RI "std::string \fBIceBRG::join_strings\fP (const std::string &s1, const std::string &s2)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. To> std::string \fBIceBRG::join_strings\fP (const std::string &s1, const std::string &s2, const std::string &s3, To\&.\&.\&.so)"
.br
.ti -1c
.RI "std::string \fBIceBRG::join_path\fP (const std::string &s1, const std::string &s2)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. To> std::string \fBIceBRG::join_path\fP (const std::string &s1, const std::string &s2, const std::string &s3, To\&.\&.\&.so)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
