.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/container/labeled_array/labeled_array_col_reference.hpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/container/labeled_array/labeled_array_col_reference.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <utility>\fP
.br
\fC#include <boost/type_traits/is_convertible\&.hpp>\fP
.br
\fC#include 'IceBRG_main/container/labeled_array\&.hpp'\fP
.br
\fC#include 'IceBRG_main/utility\&.hpp'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBIceBRG::labeled_array_col_reference< labeled_array_type, T_col_type >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
