.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_lensing/lensing_profile_extension_functors.hpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_lensing/lensing_profile_extension_functors.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'IceBRG_main/units/unit_conversions\&.hpp'\fP
.br
\fC#include 'IceBRG_main/units/units\&.hpp'\fP
.br
\fC#include 'IceBRG_main/common\&.h'\fP
.br
\fC#include 'IceBRG_main/math/calculus/integrate\&.hpp'\fP
.br
\fC#include 'IceBRG_physics/astro\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBIceBRG::projected_density_functor< name >\fP"
.br
.ti -1c
.RI "class \fBIceBRG::cylindrical_density_functor< name >\fP"
.br
.ti -1c
.RI "class \fBIceBRG::offset_ring_dens_functor< name >\fP"
.br
.ti -1c
.RI "class \fBIceBRG::offset_circ_dens_functor< name >\fP"
.br
.ti -1c
.RI "class \fBIceBRG::offset_Delta_Sigma_functor< name >\fP"
.br
.ti -1c
.RI "class \fBIceBRG::quick_offset_Delta_Sigma_functor< name >\fP"
.br
.ti -1c
.RI "class \fBIceBRG::group_Delta_Sigma_weight_functor< name >\fP"
.br
.ti -1c
.RI "class \fBIceBRG::shifted_Delta_Sigma_weight_functor< name >\fP"
.br
.ti -1c
.RI "class \fBIceBRG::shifted_Delta_Sigma_circ_functor< name >\fP"
.br
.ti -1c
.RI "class \fBIceBRG::shifted_Delta_Sigma_functor< name >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
