.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_lensing/lensing_tNFW_caches.h" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_lensing/lensing_tNFW_caches.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'IceBRG_main/common\&.h'\fP
.br
\fC#include 'IceBRG_main/math/cache/cache_3d\&.hpp'\fP
.br
\fC#include 'IceBRG_main/math/cache/cache_4d\&.hpp'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBIceBRG::tNFW_sig_cache\fP"
.br
.ti -1c
.RI "class \fBIceBRG::tNFW_offset_sig_cache\fP"
.br
.ti -1c
.RI "class \fBIceBRG::tNFW_group_sig_cache\fP"
.br
.ti -1c
.RI "class \fBIceBRG::tNFW_shifted_sig_cache\fP"
.br
.ti -1c
.RI "class \fBIceBRG::tNFW_Sigma_cache\fP"
.br
.ti -1c
.RI "class \fBIceBRG::tNFW_offset_Sigma_cache\fP"
.br
.ti -1c
.RI "class \fBIceBRG::tNFW_group_Sigma_cache\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
