.TH "/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_get_unmasked_fractions/load_pixel_table.h" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_get_unmasked_fractions/load_pixel_table.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBunpack_fits\fP (const std::string &filename)"
.br
.ti -1c
.RI "void \fBdelete_file\fP (const std::string &filename)"
.br
.ti -1c
.RI "std::vector< std::vector< bool > > \fBload_pixel_table\fP (const std::string &filename)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void delete_file (const std::string &filename)"

.SS "std::vector<std::vector<bool> > load_pixel_table (const std::string &filename)"

.SS "std::string unpack_fits (const std::string &filename)"

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
