.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_lensing/magnification/mag_global_values.h" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_lensing/magnification/mag_global_values.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'IceBRG_main/units/unit_conversions\&.hpp'\fP
.br
\fC#include 'IceBRG_main/math/misc_math\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::mag_m_counting_min\fP = 19"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::mag_m_counting_max\fP = 24\&.7"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::mag_m_min\fP = 20"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::mag_m_max\fP = 24\&.7"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::mag_m_step\fP = 0\&.1"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::mag_z_min\fP = 0\&.2"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::mag_z_max\fP = 4\&.0"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::mag_z_step\fP = 0\&.01"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::mag_lens_T_min\fP = 2\&.0"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::mag_lens_T_max\fP = 4\&.0"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::mag_min_count\fP = 0\&.1"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
