.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_lensing/magnification/mag_weight_integral_cache.cpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_lensing/magnification/mag_weight_integral_cache.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include 'IceBRG_main/common\&.h'\fP
.br
\fC#include 'IceBRG_main/math/calculus/integrate\&.hpp'\fP
.br
\fC#include 'IceBRG_lensing/magnification/expected_count_cache\&.h'\fP
.br
\fC#include 'IceBRG_lensing/magnification/mag_global_values\&.h'\fP
.br
\fC#include 'IceBRG_lensing/magnification/magnification_functors\&.h'\fP
.br
\fC#include 'mag_weight_integral_cache\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDEFINE_BRG_CACHE_STATIC_VARS\fP (mag_weight_integral_cache, 0\&.2, \fBIceBRG::mag_z_max\fP-0\&.01, 0\&.01)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "DEFINE_BRG_CACHE_STATIC_VARS (mag_weight_integral_cache, 0\&.2, \fBIceBRG::mag_z_max\fP-0\&.01, 0\&.01)"

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
