.TH "/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_catalogue_fetching/CFHTLenS_Mag_fetching_data/magic_values.py" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_catalogue_fetching/CFHTLenS_Mag_fetching_data/magic_values.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCFHTLenS_Mag_fetching_data\&.magic_values\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBCFHTLenS_Mag_fetching_data\&.magic_values\&.full_tables_path\fP = 'full_tables/'"
.br
.ti -1c
.RI "string \fBCFHTLenS_Mag_fetching_data\&.magic_values\&.filtered_tables_path\fP = 'filtered_tables/'"
.br
.ti -1c
.RI "string \fBCFHTLenS_Mag_fetching_data\&.magic_values\&.spec_matched_tables_path\fP = 'spec_matched_tables/'"
.br
.ti -1c
.RI "string \fBCFHTLenS_Mag_fetching_data\&.magic_values\&.base_good_fields_filename\fP = 'good_fields_list\&.txt'"
.br
.ti -1c
.RI "string \fBCFHTLenS_Mag_fetching_data\&.magic_values\&.base_bad_fields_filename\fP = 'bad_fields_list\&.txt'"
.br
.ti -1c
.RI "string \fBCFHTLenS_Mag_fetching_data\&.magic_values\&.base_all_fields_filename\fP = 'fields_list\&.txt'"
.br
.ti -1c
.RI "string \fBCFHTLenS_Mag_fetching_data\&.magic_values\&.spec_matched_output_file\fP = 'all_matched_galaxies\&.dat'"
.br
.ti -1c
.RI "string \fBCFHTLenS_Mag_fetching_data\&.magic_values\&.query_field_replace_tag\fP = 'REPLACEME_FIELD'"
.br
.ti -1c
.RI "string \fBCFHTLenS_Mag_fetching_data\&.magic_values\&.query_i_or_y_replace_tag\fP = 'REPLACEME_I_OR_Y'"
.br
.ti -1c
.RI "string \fBCFHTLenS_Mag_fetching_data\&.magic_values\&.command_output_replace_tag\fP = 'REPLACEME_OUTPUT_NAME'"
.br
.ti -1c
.RI "string \fBCFHTLenS_Mag_fetching_data\&.magic_values\&.command_query_replace_tag\fP = 'REPLACEME_QUERY'"
.br
.ti -1c
.RI "string \fBCFHTLenS_Mag_fetching_data\&.magic_values\&.input_replace_tag\fP = 'REPLACEME_INPUT'"
.br
.ti -1c
.RI "string \fBCFHTLenS_Mag_fetching_data\&.magic_values\&.output_replace_tag\fP = 'REPLACEME_OUTPUT'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
