.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_lensing/magnification/magnification_alpha.h" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_lensing/magnification/magnification_alpha.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'IceBRG_main/common\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBflt_type\fP \fBIceBRG::magnification_alpha\fP (const \fBflt_type\fP &m, const \fBflt_type\fP &z)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
