.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_lensing/magnification/magnification_functors.cpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_lensing/magnification/magnification_functors.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'IceBRG_main/common\&.h'\fP
.br
\fC#include 'IceBRG_main/math/misc_math\&.hpp'\fP
.br
\fC#include 'IceBRG_main/units/units\&.hpp'\fP
.br
\fC#include 'IceBRG_physics/astro\&.h'\fP
.br
\fC#include 'IceBRG_lensing/magnification/expected_count_cache\&.h'\fP
.br
\fC#include 'IceBRG_lensing/magnification/magnification_alpha\&.h'\fP
.br
\fC#include 'IceBRG_lensing/magnification/magnification_functors\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::test_fudge_factor\fP = 1\&."
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
