.TH "/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_field_stats/main_field_stats.cpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_field_stats/main_field_stats.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <Eigen/Core>\fP
.br
\fC#include 'IceBRG_main/container/labeled_array\&.hpp'\fP
.br
\fC#include 'IceBRG_main/file_access/ascii_table_map\&.hpp'\fP
.br
\fC#include 'IceBRG_main/file_access/binary_archive\&.hpp'\fP
.br
\fC#include 'IceBRG_main/file_access/open_file\&.hpp'\fP
.br
\fC#include 'IceBRG_main/join_path\&.hpp'\fP
.br
\fC#include 'IceBRG_main/math/misc_math\&.hpp'\fP
.br
\fC#include 'IceBRG_main/units/unit_conversions\&.hpp'\fP
.br
\fC#include 'IceBRG_main/vector/limit_vector\&.hpp'\fP
.br
\fC#include 'get_data_directory\&.hpp'\fP
.br
\fC#include 'magic_values\&.hpp'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAKE_WEIGHT_TABLE\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBnum_good_pixels\fP (const std::vector< std::vector< bool >> &input)"
.br
.ti -1c
.RI "int \fBmain\fP (const int argc, const char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::string \fBoutput_filename\fP = 'field_lens_weights\&.dat'"
.br
.ti -1c
.RI "constexpr unsigned \fBz_bins\fP = 110"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAKE_WEIGHT_TABLE"

.SH "Function Documentation"
.PP 
.SS "int main (const intargc, const char *argv[])"
TODO (description)
.PP
\fBParameters:\fP
.RS 4
\fITODO\fP (params to be passed at command-line) 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "size_t num_good_pixels (const std::vector< std::vector< bool >> &input)\fC [inline]\fP"

.SH "Variable Documentation"
.PP 
.SS "const std::string output_filename = 'field_lens_weights\&.dat'"

.SS "constexpr unsigned z_bins = 110"

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
