.TH "/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_source_count_fitting/main_source_count_fitting.cpp" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_source_count_fitting/main_source_count_fitting.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <boost/lexical_cast\&.hpp>\fP
.br
\fC#include 'IceBRG_main/file_access/ascii_table_map\&.hpp'\fP
.br
\fC#include 'IceBRG_main/join_path\&.hpp'\fP
.br
\fC#include 'IceBRG_main/math/misc_math\&.hpp'\fP
.br
\fC#include 'IceBRG_main/math/solvers/solvers\&.hpp'\fP
.br
\fC#include 'IceBRG_main/units/units\&.hpp'\fP
.br
\fC#include 'IceBRG_main/vector/elementwise_functions\&.hpp'\fP
.br
\fC#include 'get_data_directory\&.hpp'\fP
.br
\fC#include 'magic_values\&.hpp'\fP
.br
\fC#include 'count_fitting_functor\&.hpp'\fP
.br
\fC#include 'Schechter_like_functor\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (const int argc, const char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::string \fBoutput_filename\fP = 'count_fitting_results\&.dat'"
.br
.ti -1c
.RI "const unsigned int \fBzlo\fP = 200"
.br
.ti -1c
.RI "const unsigned int \fBzstep\fP = 40"
.br
.ti -1c
.RI "const unsigned int \fBzhi\fP = 1960"
.br
.ti -1c
.RI "const double \fBz_bin_size\fP = \fBzstep\fP*0\&.01"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (const intargc, const char *argv[])"

.SH "Variable Documentation"
.PP 
.SS "const std::string output_filename = 'count_fitting_results\&.dat'"

.SS "const double z_bin_size = \fBzstep\fP*0\&.01"

.SS "const unsigned int zhi = 1960"

.SS "const unsigned int zlo = 200"

.SS "const unsigned int zstep = 40"

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
