.TH "/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_catalogue_filtering/src/main_catalogue_filtering.cpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_catalogue_filtering/src/main_catalogue_filtering.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'IceBRG_main/units/unit_conversions\&.hpp'\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'IceBRG_main/container/labeled_array\&.hpp'\fP
.br
\fC#include 'IceBRG_main/error_handling\&.h'\fP
.br
\fC#include 'IceBRG_main/file_access/binary_archive\&.hpp'\fP
.br
\fC#include 'IceBRG_main/file_access/open_file\&.hpp'\fP
.br
\fC#include 'IceBRG_main/join_path\&.hpp'\fP
.br
\fC#include 'get_data_directory\&.hpp'\fP
.br
\fC#include 'magic_values\&.hpp'\fP
.br
\fC#include 'correct_redshift_bias\&.h'\fP
.br
\fC#include 'get_filtered_indices\&.h'\fP
.br
\fC#include 'make_output_map\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (const int argc, const char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (const intargc, const char *argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
