.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/vector/make_vector.hpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/vector/make_vector.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iterator>\fP
.br
\fC#include <type_traits>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'IceBRG_main/common\&.h'\fP
.br
\fC#include 'IceBRG_main/container/coerce\&.hpp'\fP
.br
\fC#include 'IceBRG_main/utility\&.hpp'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBIceBRG::vector_defaulter< d, container, other_container >\fP"
.br
.ti -1c
.RI "struct \fBIceBRG::vector_defaulter< 1, container, other_container >\fP"
.br
.ti -1c
.RI "struct \fBIceBRG::vector_defaulter< 0, container, other_container >\fP"
.br
.ti -1c
.RI "struct \fBIceBRG::vector_zeroer< d, container, other_container >\fP"
.br
.ti -1c
.RI "struct \fBIceBRG::vector_zeroer< 1, container, other_container >\fP"
.br
.ti -1c
.RI "struct \fBIceBRG::vector_zeroer< 0, container, other_container >\fP"
.br
.ti -1c
.RI "struct \fBIceBRG::vector_valuer< d, container, value_type, other_container >\fP"
.br
.ti -1c
.RI "struct \fBIceBRG::vector_valuer< 1, container, value_type, other_container >\fP"
.br
.ti -1c
.RI "struct \fBIceBRG::vector_valuer< 0, container, value_type, other_container >\fP"
.br
.ti -1c
.RI "struct \fBIceBRG::vector_functioner< d, container, func_type, other_container >\fP"
.br
.ti -1c
.RI "struct \fBIceBRG::vector_functioner< 1, container, func_type, other_container >\fP"
.br
.ti -1c
.RI "struct \fBIceBRG::vector_functioner< 0, container, func_type, other_container >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename container > void \fBIceBRG::make_vector_default\fP (container &vec, const typename \fBcontainer::size_type\fP &d1)"
.br
.ti -1c
.RI "template<typename container , typename\&.\&.\&. Args> void \fBIceBRG::make_vector_default\fP (container &vec, const typename \fBcontainer::size_type\fP &d1, const typename \fBcontainer::size_type\fP &d2, Args\&.\&.\&.remaining_dims)"
.br
.ti -1c
.RI "template<int_type d, typename container , typename value_type , typename other_container > void \fBIceBRG::make_vector_default\fP (container &vec, const value_type &val, const other_container &other_vec)"
.br
.ti -1c
.RI "template<typename container > void \fBIceBRG::make_vector_zeroes\fP (container &vec, const typename \fBcontainer::size_type\fP &d1)"
.br
.ti -1c
.RI "template<typename container , typename\&.\&.\&. Args> void \fBIceBRG::make_vector_zeroes\fP (container &vec, const typename \fBcontainer::size_type\fP &d1, const typename \fBcontainer::size_type\fP &d2, Args\&.\&.\&.remaining_dims)"
.br
.ti -1c
.RI "template<int_type d, typename container , typename value_type , typename other_container > void \fBIceBRG::make_vector_zeroes\fP (container &vec, const value_type &val, const other_container &other_vec)"
.br
.ti -1c
.RI "template<typename container , typename val_type > void \fBIceBRG::make_vector_value\fP (container &vec, const val_type &val, const typename \fBcontainer::size_type\fP &d1)"
.br
.ti -1c
.RI "template<typename container , typename val_type , typename\&.\&.\&. Args> void \fBIceBRG::make_vector_value\fP (container &vec, const val_type &val, const typename \fBcontainer::size_type\fP &d1, const typename \fBcontainer::size_type\fP &d2, Args\&.\&.\&.remaining_dims)"
.br
.ti -1c
.RI "template<int_type d, typename container , typename value_type , typename other_container > void \fBIceBRG::make_vector_value\fP (container &vec, const value_type &val, const other_container &other_vec)"
.br
.ti -1c
.RI "template<typename container , typename func_type > void \fBIceBRG::make_vector_function\fP (container &vec, const func_type &func, const typename \fBcontainer::size_type\fP &d1)"
.br
.ti -1c
.RI "template<typename container , typename func_type , typename\&.\&.\&. Args> void \fBIceBRG::make_vector_function\fP (container &vec, const func_type &func, const typename \fBcontainer::size_type\fP &d1, const typename \fBcontainer::size_type\fP &d2, Args\&.\&.\&.remaining_dims)"
.br
.ti -1c
.RI "template<int_type d, typename container , typename func_type , typename other_container > void \fBIceBRG::make_vector_function\fP (container &vec, const func_type &func, const other_container &other_vec)"
.br
.ti -1c
.RI "template<int_type d, typename container , typename other_container > void \fBIceBRG::make_vector_coerce\fP (container &vec, const other_container &other_vec)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
