.TH "/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_catalogue_filtering/src/make_output_map.h" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_catalogue_filtering/src/make_output_map.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <functional>\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'IceBRG_main/container/labeled_array\&.hpp'\fP
.br
\fC#include 'IceBRG_main/container/table_typedefs\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBIceBRG::labeled_array\fP< double > \fBmake_output_map\fP (const \fBIceBRG::labeled_array\fP< double > &map, const std::vector< size_t > &good_indices, const \fBIceBRG::header_t\fP &header_labels, const std::map< std::string, std::function< double(double)>> &conversions)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBIceBRG::labeled_array\fP<double> make_output_map (const \fBIceBRG::labeled_array\fP< double > &map, const std::vector< size_t > &good_indices, const \fBIceBRG::header_t\fP &header_labels, const std::map< std::string, std::function< double(double)>> &conversions)"

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
