.TH "/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_catalogue_fetching/CFHTLenS_Mag_fetching_data/match_command.py" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_catalogue_fetching/CFHTLenS_Mag_fetching_data/match_command.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCFHTLenS_Mag_fetching_data\&.match_command\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBCFHTLenS_Mag_fetching_data\&.match_command\&.get_match_command\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
