.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/math/statistics/mean_weight.hpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/math/statistics/mean_weight.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <limits>\fP
.br
\fC#include <boost/accumulators/framework/accumulator_base\&.hpp>\fP
.br
\fC#include <boost/accumulators/framework/extractor\&.hpp>\fP
.br
\fC#include <boost/accumulators/framework/features\&.hpp>\fP
.br
\fC#include <boost/accumulators/framework/parameters/sample\&.hpp>\fP
.br
\fC#include <boost/accumulators/statistics/count\&.hpp>\fP
.br
\fC#include <boost/accumulators/statistics/weighted_mean\&.hpp>\fP
.br
\fC#include 'IceBRG_main/common\&.h'\fP
.br
\fC#include 'IceBRG_main/math/misc_math\&.hpp'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBboost::accumulators::impl::mean_weight_accumulator< Sample >\fP"
.br
.ti -1c
.RI "struct \fBboost::accumulators::tag::mean_weight\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBboost\fP"
.br
.ti -1c
.RI "namespace \fBboost::accumulators\fP"
.br
.ti -1c
.RI "namespace \fBboost::accumulators::impl\fP"
.br
.ti -1c
.RI "namespace \fBboost::accumulators::tag\fP"
.br
.ti -1c
.RI "namespace \fBboost::accumulators::extract\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "extractor< tag::mean_weight > const \fBboost::accumulators::extract::mean_weight\fP = {}"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
