.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/vector/multi_vector.hpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/vector/multi_vector.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <memory>\fP
.br
\fC#include 'IceBRG_main/utility\&.hpp'\fP
.br
\fC#include 'IceBRG_main/vector/elementwise_functions\&.hpp'\fP
.br
\fC#include 'IceBRG_main/vector/summary_functions\&.hpp'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBIceBRG::multi_vector< T, A >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , typename A > void \fBIceBRG::swap\fP (multi_vector< T, A > &v1, multi_vector< T, A > &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 , typename A2 > const multi_vector< T1, A1 > \fBIceBRG::operator+\fP (multi_vector< T1, A1 > v1, const multi_vector< T2, A2 > &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 , typename A2 > const multi_vector< T1, A1 > \fBIceBRG::operator+\fP (multi_vector< T1, A1 > v1, const std::vector< T2, A2 > &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 , typename A2 > const multi_vector< T1, A1 > \fBIceBRG::operator+\fP (const std::vector< T1, A1 > &v1, multi_vector< T2, A2 > v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 > const multi_vector< T1, A1 > \fBIceBRG::operator+\fP (multi_vector< T1, A1 > v1, T2 v2)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename A2 > const multi_vector< T2, A2 > \fBIceBRG::operator+\fP (T1 v1, multi_vector< T2, A2 > v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 , typename A2 > const multi_vector< T1, A1 > \fBIceBRG::operator-\fP (multi_vector< T1, A1 > v1, const multi_vector< T2, A2 > &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 , typename A2 > const multi_vector< T1, A1 > \fBIceBRG::operator-\fP (multi_vector< T1, A1 > v1, const std::vector< T2, A2 > &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 , typename A2 > const multi_vector< T1, A1 > \fBIceBRG::operator-\fP (const std::vector< T1, A1 > &v1, multi_vector< T2, A2 > v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 > const multi_vector< T1, A1 > \fBIceBRG::operator-\fP (multi_vector< T1, A1 > v1, T2 v2)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename A2 > const multi_vector< T2, A2 > \fBIceBRG::operator-\fP (T1 v1, multi_vector< T2, A2 > v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 , typename A2 > const multi_vector< T1, A1 > \fBIceBRG::operator*\fP (multi_vector< T1, A1 > v1, const multi_vector< T2, A2 > &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 , typename A2 > const multi_vector< T1, A1 > \fBIceBRG::operator*\fP (multi_vector< T1, A1 > v1, const std::vector< T2, A2 > &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 , typename A2 > const multi_vector< T1, A1 > \fBIceBRG::operator*\fP (const std::vector< T1, A1 > &v1, multi_vector< T2, A2 > v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 > const multi_vector< T1, A1 > \fBIceBRG::operator*\fP (multi_vector< T1, A1 > v1, T2 v2)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename A2 > const multi_vector< T2, A2 > \fBIceBRG::operator*\fP (T1 v1, multi_vector< T2, A2 > v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 , typename A2 > const multi_vector< T1, A1 > \fBIceBRG::operator/\fP (multi_vector< T1, A1 > v1, const multi_vector< T2, A2 > &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 , typename A2 > const multi_vector< T1, A1 > \fBIceBRG::operator/\fP (multi_vector< T1, A1 > v1, const std::vector< T2, A2 > &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 , typename A2 > const multi_vector< T1, A1 > \fBIceBRG::operator/\fP (const std::vector< T1, A1 > &v1, multi_vector< T2, A2 > v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 > const multi_vector< T1, A1 > \fBIceBRG::operator/\fP (multi_vector< T1, A1 > v1, T2 v2)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename A2 > const multi_vector< T2, A2 > \fBIceBRG::operator/\fP (T1 v1, multi_vector< T2, A2 > v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 , typename A2 > const std::vector< bool > & \fBIceBRG::operator==\fP (const multi_vector< T1, A1 > &v1, const multi_vector< T2, A2 > &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 > const std::vector< bool > & \fBIceBRG::operator==\fP (const multi_vector< T1, A1 > &v1, const T2 v2)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename A2 > const std::vector< bool > & \fBIceBRG::operator==\fP (const T1 v1, const multi_vector< T2, A2 > &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 , typename A2 > const std::vector< bool > & \fBIceBRG::operator!=\fP (const multi_vector< T1, A1 > &v1, const multi_vector< T2, A2 > &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 > const std::vector< bool > & \fBIceBRG::operator!=\fP (const multi_vector< T1, A1 > &v1, const T2 v2)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename A2 > const std::vector< bool > & \fBIceBRG::operator!=\fP (const T1 v1, const multi_vector< T2, A2 > &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 , typename A2 > const std::vector< bool > & \fBIceBRG::operator<\fP (const multi_vector< T1, A1 > &v1, const multi_vector< T2, A2 > &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 > const std::vector< bool > & \fBIceBRG::operator<\fP (const multi_vector< T1, A1 > &v1, const T2 v2)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename A2 > const std::vector< bool > & \fBIceBRG::operator<\fP (const T1 v1, const multi_vector< T2, A2 > &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 , typename A2 > const std::vector< bool > & \fBIceBRG::operator>\fP (const multi_vector< T1, A1 > &v1, const multi_vector< T2, A2 > &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 > const std::vector< bool > & \fBIceBRG::operator>\fP (const multi_vector< T1, A1 > &v1, const T2 v2)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename A2 > const std::vector< bool > & \fBIceBRG::operator>\fP (const T1 v1, const multi_vector< T2, A2 > &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 , typename A2 > const std::vector< bool > & \fBIceBRG::operator<=\fP (const multi_vector< T1, A1 > &v1, const multi_vector< T2, A2 > &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 > const std::vector< bool > & \fBIceBRG::operator<=\fP (const multi_vector< T1, A1 > &v1, T2 v2)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename A2 > const std::vector< bool > & \fBIceBRG::operator<=\fP (const T1 v1, const multi_vector< T2, A2 > &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 , typename A2 > const std::vector< bool > & \fBIceBRG::operator>=\fP (const multi_vector< T1, A1 > &v1, const multi_vector< T2, A2 > &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 > const std::vector< bool > & \fBIceBRG::operator>=\fP (const multi_vector< T1, A1 > &v1, const T2 v2)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename A2 > const std::vector< bool > & \fBIceBRG::operator>=\fP (const T1 v1, const multi_vector< T2, A2 > &v2)"
.br
.ti -1c
.RI "template<typename T , typename A , typename T_o , typename A_o > multi_vector< T, A > \fBIceBRG::min\fP (multi_vector< T, A > v1, const multi_vector< T_o, A_o > &v2)"
.br
.ti -1c
.RI "template<typename T , typename A , typename T_o , typename A_o > multi_vector< T, A > \fBIceBRG::min\fP (multi_vector< T, A > v1, const std::vector< T_o, A_o > &v2)"
.br
.ti -1c
.RI "template<typename T , typename A , typename T_o , typename A_o > multi_vector< T, A > \fBIceBRG::min\fP (const std::vector< T, A > &v1, const multi_vector< T_o, A_o > &v2)"
.br
.ti -1c
.RI "template<typename T , typename T_o , typename A_o > multi_vector< T_o, A_o > \fBIceBRG::min\fP (T v1, multi_vector< T_o, A_o > v2)"
.br
.ti -1c
.RI "template<typename T , typename A , typename T_o > multi_vector< T, A > \fBIceBRG::min\fP (multi_vector< T, A > v1, const T_o v2)"
.br
.ti -1c
.RI "template<typename T , typename A , typename T_o , typename A_o > multi_vector< T, A > \fBIceBRG::max\fP (multi_vector< T, A > v1, const multi_vector< T_o, A_o > &v2)"
.br
.ti -1c
.RI "template<typename T , typename A , typename T_o , typename A_o > multi_vector< T, A > \fBIceBRG::max\fP (multi_vector< T, A > v1, const std::vector< T_o, A_o > &v2)"
.br
.ti -1c
.RI "template<typename T , typename A , typename T_o , typename A_o > multi_vector< T, A > \fBIceBRG::max\fP (const std::vector< T, A > &v1, const multi_vector< T_o, A_o > &v2)"
.br
.ti -1c
.RI "template<typename T , typename T_o , typename A_o > multi_vector< T_o, A_o > \fBIceBRG::max\fP (const T v1, multi_vector< T_o, A_o > v2)"
.br
.ti -1c
.RI "template<typename T , typename A , typename T_o > multi_vector< T, A > \fBIceBRG::max\fP (multi_vector< T, A > v1, const T_o v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 , typename A2 > const multi_vector< T1, A1 > \fBIceBRG::pow\fP (multi_vector< T1, A1 > v1, const multi_vector< T2, A2 > &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 > const multi_vector< T1, A1 > \fBIceBRG::pow\fP (const multi_vector< T1, A1 > &v1, const T2 &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename A2 > const multi_vector< T2, A2 > \fBIceBRG::pow\fP (const T1 &v1, multi_vector< T2, A2 > v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 , typename A2 > const multi_vector< T1, A1 > \fBIceBRG::safe_pow\fP (multi_vector< T1, A1 > v1, const multi_vector< T2, A2 > &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename A1 , typename T2 > const multi_vector< T1, A1 > \fBIceBRG::safe_pow\fP (const multi_vector< T1, A1 > &v1, const T2 &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename A2 > const multi_vector< T2, A2 > \fBIceBRG::safe_pow\fP (const T1 &v1, multi_vector< T2, A2 > v2)"
.br
.ti -1c
.RI "template<typename T , typename A > const multi_vector< T, A > \fBIceBRG::operator-\fP (multi_vector< T, A > v)"
.br
.ti -1c
.RI "template<typename T , typename A > const multi_vector< T, A > \fBIceBRG::abs\fP (multi_vector< T, A > v)"
.br
.ti -1c
.RI "template<typename T , typename A > const multi_vector< T, A > \fBIceBRG::sqrt\fP (multi_vector< T, A > v)"
.br
.ti -1c
.RI "template<typename T , typename A > const multi_vector< T, A > \fBIceBRG::safe_sqrt\fP (multi_vector< T, A > v)"
.br
.ti -1c
.RI "template<typename T , typename A > const multi_vector< T, A > \fBIceBRG::exp\fP (multi_vector< T, A > v)"
.br
.ti -1c
.RI "template<typename T , typename A > const multi_vector< T, A > \fBIceBRG::square\fP (multi_vector< T, A > v)"
.br
.ti -1c
.RI "template<typename T , typename A > const multi_vector< T, A > \fBIceBRG::cube\fP (multi_vector< T, A > v)"
.br
.ti -1c
.RI "template<typename T , typename A > const multi_vector< T, A > \fBIceBRG::quart\fP (multi_vector< T, A > v)"
.br
.ti -1c
.RI "template<typename T , typename A > const multi_vector< T, A > \fBIceBRG::inverse\fP (multi_vector< T, A > v)"
.br
.ti -1c
.RI "template<typename T , typename A > const multi_vector< T, A > \fBIceBRG::inv_square\fP (multi_vector< T, A > v)"
.br
.ti -1c
.RI "template<typename T , typename A > const multi_vector< T, A > \fBIceBRG::inv_cube\fP (multi_vector< T, A > v)"
.br
.ti -1c
.RI "template<typename T , typename A > const multi_vector< T, A > \fBIceBRG::inv_quart\fP (multi_vector< T, A > v)"
.br
.ti -1c
.RI "template<typename T , typename A > const multi_vector< T, A > \fBIceBRG::safe_d\fP (multi_vector< T, A > v)"
.br
.ti -1c
.RI "template<typename T , typename A > const T \fBIceBRG::sum\fP (const \fBIceBRG::multi_vector\fP< T, A > &v)"
.br
.ti -1c
.RI "template<typename T , typename A > const T \fBIceBRG::product\fP (const \fBIceBRG::multi_vector\fP< T, A > &v)"
.br
.ti -1c
.RI "template<typename T , typename A > const T \fBIceBRG::mean\fP (const \fBIceBRG::multi_vector\fP< T, A > &v)"
.br
.ti -1c
.RI "template<typename T , typename A > const T \fBIceBRG::std\fP (const \fBIceBRG::multi_vector\fP< T, A > &v)"
.br
.ti -1c
.RI "template<typename T , typename A > const T \fBIceBRG::stddev\fP (const \fBIceBRG::multi_vector\fP< T, A > &v)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
