.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/file_access/open_file.hpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/file_access/open_file.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'IceBRG_main/common\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename stream_type > void \fBIceBRG::open_file\fP (stream_type &stream, const std::string &name)"
.br
.ti -1c
.RI "template<typename stream_type > void \fBIceBRG::open_file_input\fP (stream_type &stream, const std::string &name)"
.br
.ti -1c
.RI "template<typename stream_type > void \fBIceBRG::open_file_output\fP (stream_type &stream, const std::string &name)"
.br
.ti -1c
.RI "template<typename stream_type > void \fBIceBRG::open_file_io\fP (stream_type &stream, const std::string &name)"
.br
.ti -1c
.RI "template<typename stream_type > void \fBIceBRG::open_file_append\fP (stream_type &stream, const std::string &name)"
.br
.ti -1c
.RI "template<typename stream_type > void \fBIceBRG::open_bin_file\fP (stream_type &stream, const std::string &name)"
.br
.ti -1c
.RI "void \fBIceBRG::open_bin_file\fP (std::fstream &stream, const std::string &name)"
.br
.ti -1c
.RI "template<typename stream_type > void \fBIceBRG::open_bin_file_input\fP (stream_type &stream, const std::string &name)"
.br
.ti -1c
.RI "template<typename stream_type > void \fBIceBRG::open_bin_file_io\fP (stream_type &stream, const std::string &name)"
.br
.ti -1c
.RI "template<typename stream_type > void \fBIceBRG::open_bin_file_output\fP (stream_type &stream, const std::string &name)"
.br
.ti -1c
.RI "template<typename stream_type > void \fBIceBRG::open_bin_file_append\fP (stream_type &stream, const std::string &name)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
