.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_lensing/pair_bins_summary.cpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_lensing/pair_bins_summary.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <boost/archive/text_oarchive\&.hpp>\fP
.br
\fC#include <boost/archive/text_iarchive\&.hpp>\fP
.br
\fC#include 'IceBRG_main/common\&.h'\fP
.br
\fC#include 'IceBRG_main/file_access/ascii_table_map\&.hpp'\fP
.br
\fC#include 'IceBRG_main/file_access/open_file\&.hpp'\fP
.br
\fC#include 'IceBRG_main/math/misc_math\&.hpp'\fP
.br
\fC#include 'IceBRG_main/units/apply_unitconvs\&.hpp'\fP
.br
\fC#include 'IceBRG_main/units/units\&.hpp'\fP
.br
\fC#include 'IceBRG_main/utility\&.hpp'\fP
.br
\fC#include 'IceBRG_main/vector/make_vector\&.hpp'\fP
.br
\fC#include 'IceBRG_main/vector/limit_vector\&.hpp'\fP
.br
\fC#include 'IceBRG_main/vector/summary_functions\&.hpp'\fP
.br
\fC#include 'IceBRG_lensing/pair_bin\&.h'\fP
.br
\fC#include 'IceBRG_lensing/pair_binner\&.h'\fP
.br
\fC#include 'pair_bins_summary\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
