.TH "/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_gg_lensing/pass_configs_to_binner.h" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_gg_lensing/pass_configs_to_binner.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'IceBRG_lensing/pair_binner\&.h'\fP
.br
\fC#include 'gg_lensing_config\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBIceBRG::pair_binner\fP \fBpass_configs_to_binner\fP (const \fBgg_lensing_config\fP &config)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBIceBRG::pair_binner\fP pass_configs_to_binner (const \fBgg_lensing_config\fP &config)"

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
