.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_physics/density_profile/point_mass_profile.h" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_physics/density_profile/point_mass_profile.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'IceBRG_main/common\&.h'\fP
.br
\fC#include 'IceBRG_physics/density_profile/density_profile\&.h'\fP
.br
\fC#include 'IceBRG_main/units/units\&.hpp'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBIceBRG::point_mass_profile\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
