.TH "/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_catalogue_fetching/CFHTLenS_Mag_fetching_data/query.py" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/exec/CFHTLenS_catalogue_fetching/CFHTLenS_Mag_fetching_data/query.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCFHTLenS_Mag_fetching_data\&.query\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBCFHTLenS_Mag_fetching_data\&.query\&.get_query\fP"
.br
.ti -1c
.RI "def \fBCFHTLenS_Mag_fetching_data\&.query\&.get_wget_command\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
