.TH "redshift_calibrator_wrapper" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
redshift_calibrator_wrapper \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <correct_redshift_bias\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBIceBRG::interpolator\fP \fBredshift_calibration_interpolator\fP = \fBIceBRG::interpolator\fP()"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "static \fBIceBRG::interpolator\fP redshift_calibrator_wrapper::redshift_calibration_interpolator = \fBIceBRG::interpolator\fP()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
