.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/external/sgsmooth.cpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/external/sgsmooth.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdexcept>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'IceBRG_main/common\&.h'\fP
.br
\fC#include 'IceBRG_main/math/misc_math\&.hpp'\fP
.br
\fC#include 'sgsmooth\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBIceBRG::sgsmooth::float_mat\fP"
.br
.RI "\fItwo dimensional floating point array \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.ti -1c
.RI "namespace \fBIceBRG::sgsmooth\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::vector< size_t > \fBIceBRG::sgsmooth::uint_vect\fP"
.br
.RI "\fIcomfortable array of ints; \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBIceBRG::sgsmooth::permute\fP (float_mat &A, uint_vect &idx)"
.br
.RI "\fI\fBpermute()\fP orders the rows of A to match the integers in the index array\&. \fP"
.ti -1c
.RI "float_mat \fBIceBRG::sgsmooth::operator*\fP (const float_mat &a, const float_mat &b)"
.br
.RI "\fImatrix multiplication\&. \fP"
.ti -1c
.RI "\fBflt_vector_type\fP \fBIceBRG::sgsmooth::sg_smooth\fP (const \fBflt_vector_type\fP &v, const size_t &width, const size_t &deg)"
.br
.RI "\fIsavitzky golay smoothing\&. \fP"
.ti -1c
.RI "std::vector< \fBflt_type\fP > \fBIceBRG::sgsmooth::sg_derivative\fP (const std::vector< \fBflt_type\fP > &v, const size_t &width, const size_t &deg, const \fBflt_type\fP &h)"
.br
.RI "\fIsavitzky golay smoothed numerical derivative\&. \fP"
.ti -1c
.RI "void \fBIceBRG::sgsmooth::sgs_error\fP (const char *errmsg)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
