.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/external/sgsmooth.h" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/external/sgsmooth.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'IceBRG_main/common\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.ti -1c
.RI "namespace \fBIceBRG::sgsmooth\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBflt_vector_type\fP \fBIceBRG::sgsmooth::sg_smooth\fP (const \fBflt_vector_type\fP &v, const size_t &width, const size_t &deg)"
.br
.RI "\fIsavitzky golay smoothing\&. \fP"
.ti -1c
.RI "\fBflt_vector_type\fP \fBIceBRG::sgsmooth::sg_derivative\fP (const \fBflt_vector_type\fP &input, const size_t &window, const size_t &order, const \fBflt_type\fP &delta=1\&.0)"
.br
.ti -1c
.RI "void \fBIceBRG::sgsmooth::sgs_error\fP (const char *errmsg)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
