.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_lensing/shifting/shifting_cache.cpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_lensing/shifting/shifting_cache.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include 'IceBRG_main/common\&.h'\fP
.br
\fC#include 'IceBRG_main/math/safe_math\&.hpp'\fP
.br
\fC#include 'IceBRG_lensing/shifting/shifting_loader\&.h'\fP
.br
\fC#include 'shifting_cache\&.h'\fP
.br
\fC#include 'IceBRG_main/units/unit_conversions\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDEFINE_BRG_CACHE_2D_STATIC_VARS\fP (shifting_cache, 0, 3800 *\fBIceBRG::unitconv::amintorad\fP, 1 *\fBIceBRG::unitconv::amintorad\fP, 0\&.1, 1\&.5, 0\&.1)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "DEFINE_BRG_CACHE_2D_STATIC_VARS (shifting_cache, 0, 3800 *\fBIceBRG::unitconv::amintorad\fP, 1 *\fBIceBRG::unitconv::amintorad\fP, 0\&.1, 1\&.5, 0\&.1)"

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
