.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_lensing/source_galaxy.h" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_lensing/source_galaxy.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'IceBRG_lensing/source_obj\&.hpp'\fP
.br
\fC#include 'IceBRG_physics/sky_obj/galaxy\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBIceBRG::source_galaxy\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
