.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/external/tk_spline.cpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/external/tk_spline.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include 'tk_spline\&.h'\fP
.br
\fC#include 'IceBRG_main/utility\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
simple cubic spline interpolation library without external dependencies
.PP
Split into \&.h and \&.cpp by Bryan Gillis July 16, 2014 
.PP
 Copyright (C) 2011, 2014 Tino Kluge (ttk448 at gmail\&.com)
.PP
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version\&.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU General Public License 
.SS "along with this program\&. If not, see http://www.gnu.org/licenses/\&."

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
