.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_physics/sky_obj_with_density_profile/tNFW_galaxy.cpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_physics/sky_obj_with_density_profile/tNFW_galaxy.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'tNFW_galaxy\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
