.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/file_access/trim_comments.hpp" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/file_access/trim_comments.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'IceBRG_main/common\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename streamtype > void \fBIceBRG::trim_comments_one_line\fP (streamtype &stream)"
.br
.ti -1c
.RI "template<typename streamtype > void \fBIceBRG::trim_comments_all_at_top\fP (streamtype &stream)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
