.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_lensing/two_halo_term_functions.hpp" 3 "Tue Jul 7 2015" "Version 0.9.0" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_lensing/two_halo_term_functions.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include 'IceBRG_main/common\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.ti -1c
.RI "namespace \fBIceBRG::two_halo_calcs\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBflt_type\fP \fBIceBRG::two_halo_calcs::nu_prime\fP (\fBflt_type\fP nu)"
.br
.ti -1c
.RI "\fBflt_type\fP \fBIceBRG::two_halo_calcs::nu_f_nu\fP (\fBflt_type\fP nu)"
.br
.ti -1c
.RI "\fBflt_type\fP \fBIceBRG::two_halo_calcs::b_of_nu\fP (const \fBflt_type\fP &nu)"
.br
.ti -1c
.RI "\fBflt_type\fP \fBIceBRG::two_halo_calcs::_W_R_k\fP (const \fBflt_type\fP &R, const \fBflt_type\fP &k)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::two_halo_calcs::delta_c\fP = 1\&.686"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::two_halo_calcs::A\fP = 1\&."
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::two_halo_calcs::a\fP = 0\&.707"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::two_halo_calcs::p\fP = 0\&.3"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
