.TH "/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/units/unit_conversions.hpp" 3 "Thu Jul 9 2015" "Version 0.9.2" "CFHTLenS_Magnification" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/disk2/brg/git/Magnification_Public/src/lib/IceBRG_main/units/unit_conversions.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'IceBRG_main/common\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIceBRG\fP"
.br
.ti -1c
.RI "namespace \fBIceBRG::unitconv\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mtom\fP = 1"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mtomm\fP = 1e3"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mmtom\fP = 1 / mtomm"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mtocm\fP = 1e2"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::cmtom\fP = 1 / mtocm"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mtoum\fP = 1e6"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::umtom\fP = 1 / mtoum"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mtonm\fP = 1e9"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::nmtom\fP = 1 / mtonm"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mtoangstrom\fP = 1e10"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::angstromtom\fP = 1 / mtoangstrom"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mtokm\fP = 1e-3"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::kmtom\fP = 1 / mtokm"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::ltyrtom\fP = 9460730472580800"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mtoltyr\fP = 1 / ltyrtom"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::AUtom\fP = 149597870700"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mtoAU\fP = 1 / AUtom"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::pctom\fP = AUtom * 648000 / \fBpi\fP"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mtopc\fP = 1 / pctom"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::kpctom\fP = 1000 * pctom"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mtokpc\fP = 1 / kpctom"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::Mpctom\fP = 1000000 * pctom"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mtoMpc\fP = 1 / Mpctom"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mitom\fP = 1609\&.344"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mtomi\fP = 1 / mitom"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::Mmitom\fP = 1e6 * mitom"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mtoMmi\fP = 1 / Mmitom"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::fttom\fP = 0\&.3048"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mtoft\fP = 1 / fttom"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::intom\fP = \&.0254"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mtoin\fP = 1 / intom"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::ydtom\fP = 0\&.9144"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mtoyd\fP = 1 / ydtom"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::stos\fP = 1"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::stocs\fP = 1e2"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::cstos\fP = 1 / stocs"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::stoms\fP = 1e3"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mstos\fP = 1 / stoms"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::stous\fP = 1e6"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::ustos\fP = 1 / stous"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::stons\fP = 1e9"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::nstos\fP = 1 / stons"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mintos\fP = 60"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::stomin\fP = 1 / mintos"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::hrtos\fP = mintos * 60"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::stohr\fP = 1 / hrtos"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::daytos\fP = hrtos * 24"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::stoday\fP = 1 / daytos"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::weektos\fP = daytos * 7"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::stoweek\fP = 1 / weektos"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::yrtos\fP = daytos * 365\&.25"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::stoyr\fP = 1 / yrtos"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::monthtos\fP = yrtos / 12"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::stomonth\fP = 1 / monthtos"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::kyrtos\fP = yrtos * 1e3"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::stokyr\fP = 1 / kyrtos"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::Myrtos\fP = yrtos * 1e6"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::stoMyr\fP = 1 / Myrtos"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::Gyrtos\fP = yrtos * 1e9"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::stoGyr\fP = 1 / Gyrtos"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mpstomps\fP = 1"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mpstokmps\fP = 1e-3"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::kmpstomps\fP = 1 / mpstokmps"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::ctomps\fP = 299792458"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mpstoc\fP = 1 / ctomps"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::mpstomiphr\fP = mtomi / stohr"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::miphr\fP = 1 / mpstomiphr"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::kgtokg\fP = 1"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::kgtogm\fP = 1e3"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::gmtokg\fP = 1 / kgtogm"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::Mearthtokg\fP = 5\&.9736e24"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::kgtoMearth\fP = 1 / Mearthtokg"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::Msuntokg\fP = 1\&.9891e30"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::kgtoMsun\fP = 1 / Msuntokg"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::kgtottMsun\fP = kgtoMsun * 1e-10"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::ttMsuntokg\fP = 1 / kgtottMsun"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::KtoK\fP = 1"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::KtodegF\fP = 1\&.8"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::degCtoK\fP = KtoK"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::KtodegC\fP = 1 / degCtoK"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::degFtoK\fP = 1 / KtodegF"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::degCtodegF\fP = KtodegF"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::degFtodegC\fP = degFtoK"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::KtodegR\fP = KtodegF"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::degRtoK\fP = degFtoK"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::degCtodegR\fP = KtodegF"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::degRtodegC\fP = degFtoK"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::radtorad\fP = 1"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::degtorad\fP = \fBpi\fP / 180"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::radtodeg\fP = 1 / degtorad"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::degtoamin\fP = 60"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::amintodeg\fP = 1 / degtoamin"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::amintoasec\fP = 60"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::asectoamin\fP = 1 / amintoasec"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::asectodeg\fP = asectoamin * amintodeg"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::degtoasec\fP = 1 / asectodeg"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::amintorad\fP = amintodeg * degtorad"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::radtoamin\fP = 1 / amintorad"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::asectorad\fP = asectodeg * degtorad"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::radtoasec\fP = 1 / asectorad"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::CtoC\fP = 1"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::Ctoesu\fP = 6\&.241509324e18"
.br
.ti -1c
.RI "constexpr \fBflt_type\fP \fBIceBRG::unitconv::esutoC\fP = 1 / Ctoesu"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CFHTLenS_Magnification from the source code\&.
